// Code generated by Fern. DO NOT EDIT.

package client

import (
	auth "github.com/MauroDruwel/weathercloud-go/auth"
	core "github.com/MauroDruwel/weathercloud-go/core"
	devicehistory "github.com/MauroDruwel/weathercloud-go/devicehistory"
	devicelive "github.com/MauroDruwel/weathercloud-go/devicelive"
	forecast "github.com/MauroDruwel/weathercloud-go/forecast"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	map_ "github.com/MauroDruwel/weathercloud-go/map_"
	metar "github.com/MauroDruwel/weathercloud-go/metar"
	option "github.com/MauroDruwel/weathercloud-go/option"
	stations "github.com/MauroDruwel/weathercloud-go/stations"
)

type WeathercloudClient struct {
	Auth          *auth.Client
	DeviceLive    *devicelive.Client
	DeviceHistory *devicehistory.Client
	Forecast      *forecast.Client
	Map           *map_.Client
	Stations      *stations.Client
	Metar         *metar.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewWeathercloudClient(opts ...option.RequestOption) *WeathercloudClient {
	options := core.NewRequestOptions(opts...)
	return &WeathercloudClient{
		Auth:          auth.NewClient(options),
		DeviceLive:    devicelive.NewClient(options),
		DeviceHistory: devicehistory.NewClient(options),
		Forecast:      forecast.NewClient(options),
		Map:           map_.NewClient(options),
		Stations:      stations.NewClient(options),
		Metar:         metar.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
