// Code generated by Fern. DO NOT EDIT.

package client

import (
	auth "sdk/auth"
	core "sdk/core"
	devicehistory "sdk/devicehistory"
	devicelive "sdk/devicelive"
	forecast "sdk/forecast"
	internal "sdk/internal"
	map_ "sdk/map_"
	metar "sdk/metar"
	option "sdk/option"
	stations "sdk/stations"
)

type Client struct {
	Auth          *auth.Client
	DeviceLive    *devicelive.Client
	DeviceHistory *devicehistory.Client
	Forecast      *forecast.Client
	Map           *map_.Client
	Stations      *stations.Client
	Metar         *metar.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Auth:          auth.NewClient(options),
		DeviceLive:    devicelive.NewClient(options),
		DeviceHistory: devicehistory.NewClient(options),
		Forecast:      forecast.NewClient(options),
		Map:           map_.NewClient(options),
		Stations:      stations.NewClient(options),
		Metar:         metar.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
