// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersLoginAuthRequest(t *testing.T) {
	t.Run("SetLoginFormEntity", func(t *testing.T) {
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormEntity string
		obj.SetLoginFormEntity(fernTestValueLoginFormEntity)
		assert.Equal(t, fernTestValueLoginFormEntity, obj.LoginFormEntity)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoginFormPassword", func(t *testing.T) {
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormPassword string
		obj.SetLoginFormPassword(fernTestValueLoginFormPassword)
		assert.Equal(t, fernTestValueLoginFormPassword, obj.LoginFormPassword)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLoginFormRememberMe", func(t *testing.T) {
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormRememberMe *LoginAuthRequestLoginFormRememberMe
		obj.SetLoginFormRememberMe(fernTestValueLoginFormRememberMe)
		assert.Equal(t, fernTestValueLoginFormRememberMe, obj.LoginFormRememberMe)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLoginAuthRequest(t *testing.T) {
	t.Run("SetLoginFormEntity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormEntity string

		// Act
		obj.SetLoginFormEntity(fernTestValueLoginFormEntity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoginFormPassword_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormPassword string

		// Act
		obj.SetLoginFormPassword(fernTestValueLoginFormPassword)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLoginFormRememberMe_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LoginAuthRequest{}
		var fernTestValueLoginFormRememberMe *LoginAuthRequestLoginFormRememberMe

		// Act
		obj.SetLoginFormRememberMe(fernTestValueLoginFormRememberMe)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumLoginAuthRequestLoginFormRememberMe(t *testing.T) {
	t.Run("NewFromString_0", func(t *testing.T) {
		t.Parallel()
		val, err := NewLoginAuthRequestLoginFormRememberMeFromString("0")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LoginAuthRequestLoginFormRememberMe("0"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_1", func(t *testing.T) {
		t.Parallel()
		val, err := NewLoginAuthRequestLoginFormRememberMeFromString("1")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, LoginAuthRequestLoginFormRememberMe("1"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewLoginAuthRequestLoginFormRememberMeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewLoginAuthRequestLoginFormRememberMeFromString("0")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
