// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	loginAuthRequestFieldLoginFormEntity     = big.NewInt(1 << 0)
	loginAuthRequestFieldLoginFormPassword   = big.NewInt(1 << 1)
	loginAuthRequestFieldLoginFormRememberMe = big.NewInt(1 << 2)
)

type LoginAuthRequest struct {
	// Username or email address
	LoginFormEntity string `json:"LoginForm[entity]" url:"-"`
	// Account password
	LoginFormPassword string `json:"LoginForm[password]" url:"-"`
	// Keep the user logged in
	LoginFormRememberMe *LoginAuthRequestLoginFormRememberMe `json:"LoginForm[rememberMe],omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *LoginAuthRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetLoginFormEntity sets the LoginFormEntity field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoginAuthRequest) SetLoginFormEntity(loginFormEntity string) {
	l.LoginFormEntity = loginFormEntity
	l.require(loginAuthRequestFieldLoginFormEntity)
}

// SetLoginFormPassword sets the LoginFormPassword field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoginAuthRequest) SetLoginFormPassword(loginFormPassword string) {
	l.LoginFormPassword = loginFormPassword
	l.require(loginAuthRequestFieldLoginFormPassword)
}

// SetLoginFormRememberMe sets the LoginFormRememberMe field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *LoginAuthRequest) SetLoginFormRememberMe(loginFormRememberMe *LoginAuthRequestLoginFormRememberMe) {
	l.LoginFormRememberMe = loginFormRememberMe
	l.require(loginAuthRequestFieldLoginFormRememberMe)
}

func (l *LoginAuthRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler LoginAuthRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*l = LoginAuthRequest(body)
	return nil
}

func (l *LoginAuthRequest) MarshalJSON() ([]byte, error) {
	type embed LoginAuthRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Keep the user logged in
type LoginAuthRequestLoginFormRememberMe string

const (
	LoginAuthRequestLoginFormRememberMeZero LoginAuthRequestLoginFormRememberMe = "0"
	LoginAuthRequestLoginFormRememberMeOne  LoginAuthRequestLoginFormRememberMe = "1"
)

func NewLoginAuthRequestLoginFormRememberMeFromString(s string) (LoginAuthRequestLoginFormRememberMe, error) {
	switch s {
	case "0":
		return LoginAuthRequestLoginFormRememberMeZero, nil
	case "1":
		return LoginAuthRequestLoginFormRememberMeOne, nil
	}
	var t LoginAuthRequestLoginFormRememberMe
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LoginAuthRequestLoginFormRememberMe) Ptr() *LoginAuthRequestLoginFormRememberMe {
	return &l
}
