// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetEvolutionDeviceHistoryRequest(t *testing.T) {
	t.Run("SetDevice", func(t *testing.T) {
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValueDevice string
		obj.SetDevice(fernTestValueDevice)
		assert.Equal(t, fernTestValueDevice, obj.Device)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVariable", func(t *testing.T) {
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValueVariable int
		obj.SetVariable(fernTestValueVariable)
		assert.Equal(t, fernTestValueVariable, obj.Variable)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPeriod", func(t *testing.T) {
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValuePeriod GetEvolutionDeviceHistoryRequestPeriod
		obj.SetPeriod(fernTestValuePeriod)
		assert.Equal(t, fernTestValuePeriod, obj.Period)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetEvolutionDeviceHistoryRequest(t *testing.T) {
	t.Run("SetDevice_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValueDevice string

		// Act
		obj.SetDevice(fernTestValueDevice)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVariable_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValueVariable int

		// Act
		obj.SetVariable(fernTestValueVariable)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPeriod_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetEvolutionDeviceHistoryRequest{}
		var fernTestValuePeriod GetEvolutionDeviceHistoryRequestPeriod

		// Act
		obj.SetPeriod(fernTestValuePeriod)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvolutionResponse(t *testing.T) {
	t.Run("SetStatus", func(t *testing.T) {
		obj := &EvolutionResponse{}
		var fernTestValueStatus *string
		obj.SetStatus(fernTestValueStatus)
		assert.Equal(t, fernTestValueStatus, obj.Status)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &EvolutionResponse{}
		var fernTestValueData *EvolutionResponseData
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvolutionResponse(t *testing.T) {
	t.Run("GetStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		var expected *string
		obj.Status = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStatus(), "getter should return the property value")
	})

	t.Run("GetStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		obj.Status = nil

		// Act & Assert
		assert.Nil(t, obj.GetStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStatus() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		var expected *EvolutionResponseData
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

}

func TestSettersMarkExplicitEvolutionResponse(t *testing.T) {
	t.Run("SetStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		var fernTestValueStatus *string

		// Act
		obj.SetStatus(fernTestValueStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}
		var fernTestValueData *EvolutionResponseData

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvolutionResponseData(t *testing.T) {
	t.Run("SetTimezone", func(t *testing.T) {
		obj := &EvolutionResponseData{}
		var fernTestValueTimezone *string
		obj.SetTimezone(fernTestValueTimezone)
		assert.Equal(t, fernTestValueTimezone, obj.Timezone)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSummary", func(t *testing.T) {
		obj := &EvolutionResponseData{}
		var fernTestValueSummary map[string]*EvolutionResponseDataSummaryValue
		obj.SetSummary(fernTestValueSummary)
		assert.Equal(t, fernTestValueSummary, obj.Summary)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValues", func(t *testing.T) {
		obj := &EvolutionResponseData{}
		var fernTestValueValues map[string]map[string]*EvolutionResponseDataValuesValueValue
		obj.SetValues(fernTestValueValues)
		assert.Equal(t, fernTestValueValues, obj.Values)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvolutionResponseData(t *testing.T) {
	t.Run("GetTimezone", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var expected *string
		obj.Timezone = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTimezone(), "getter should return the property value")
	})

	t.Run("GetTimezone_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		obj.Timezone = nil

		// Act & Assert
		assert.Nil(t, obj.GetTimezone(), "getter should return nil when property is nil")
	})

	t.Run("GetTimezone_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTimezone() // Should return zero value
	})

	t.Run("GetSummary", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var expected map[string]*EvolutionResponseDataSummaryValue
		obj.Summary = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSummary(), "getter should return the property value")
	})

	t.Run("GetSummary_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		obj.Summary = nil

		// Act & Assert
		assert.Nil(t, obj.GetSummary(), "getter should return nil when property is nil")
	})

	t.Run("GetSummary_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSummary() // Should return zero value
	})

	t.Run("GetValues", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var expected map[string]map[string]*EvolutionResponseDataValuesValueValue
		obj.Values = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValues(), "getter should return the property value")
	})

	t.Run("GetValues_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		obj.Values = nil

		// Act & Assert
		assert.Nil(t, obj.GetValues(), "getter should return nil when property is nil")
	})

	t.Run("GetValues_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseData
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValues() // Should return zero value
	})

}

func TestSettersMarkExplicitEvolutionResponseData(t *testing.T) {
	t.Run("SetTimezone_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var fernTestValueTimezone *string

		// Act
		obj.SetTimezone(fernTestValueTimezone)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSummary_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var fernTestValueSummary map[string]*EvolutionResponseDataSummaryValue

		// Act
		obj.SetSummary(fernTestValueSummary)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValues_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}
		var fernTestValueValues map[string]map[string]*EvolutionResponseDataValuesValueValue

		// Act
		obj.SetValues(fernTestValueValues)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("SetSamples", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueSamples *int
		obj.SetSamples(fernTestValueSamples)
		assert.Equal(t, fernTestValueSamples, obj.Samples)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSum", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueSum *float64
		obj.SetSum(fernTestValueSum)
		assert.Equal(t, fernTestValueSum, obj.Sum)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMin", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMin *float64
		obj.SetMin(fernTestValueMin)
		assert.Equal(t, fernTestValueMin, obj.Min)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinTime", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMinTime *int
		obj.SetMinTime(fernTestValueMinTime)
		assert.Equal(t, fernTestValueMinTime, obj.MinTime)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMax", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMax *float64
		obj.SetMax(fernTestValueMax)
		assert.Equal(t, fernTestValueMax, obj.Max)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxTime", func(t *testing.T) {
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMaxTime *int
		obj.SetMaxTime(fernTestValueMaxTime)
		assert.Equal(t, fernTestValueMaxTime, obj.MaxTime)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("GetSamples", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *int
		obj.Samples = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSamples(), "getter should return the property value")
	})

	t.Run("GetSamples_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.Samples = nil

		// Act & Assert
		assert.Nil(t, obj.GetSamples(), "getter should return nil when property is nil")
	})

	t.Run("GetSamples_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSamples() // Should return zero value
	})

	t.Run("GetSum", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *float64
		obj.Sum = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSum(), "getter should return the property value")
	})

	t.Run("GetSum_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.Sum = nil

		// Act & Assert
		assert.Nil(t, obj.GetSum(), "getter should return nil when property is nil")
	})

	t.Run("GetSum_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSum() // Should return zero value
	})

	t.Run("GetMin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *float64
		obj.Min = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMin(), "getter should return the property value")
	})

	t.Run("GetMin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.Min = nil

		// Act & Assert
		assert.Nil(t, obj.GetMin(), "getter should return nil when property is nil")
	})

	t.Run("GetMin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMin() // Should return zero value
	})

	t.Run("GetMinTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *int
		obj.MinTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMinTime(), "getter should return the property value")
	})

	t.Run("GetMinTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.MinTime = nil

		// Act & Assert
		assert.Nil(t, obj.GetMinTime(), "getter should return nil when property is nil")
	})

	t.Run("GetMinTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMinTime() // Should return zero value
	})

	t.Run("GetMax", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *float64
		obj.Max = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMax(), "getter should return the property value")
	})

	t.Run("GetMax_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.Max = nil

		// Act & Assert
		assert.Nil(t, obj.GetMax(), "getter should return nil when property is nil")
	})

	t.Run("GetMax_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMax() // Should return zero value
	})

	t.Run("GetMaxTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var expected *int
		obj.MaxTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMaxTime(), "getter should return the property value")
	})

	t.Run("GetMaxTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		obj.MaxTime = nil

		// Act & Assert
		assert.Nil(t, obj.GetMaxTime(), "getter should return nil when property is nil")
	})

	t.Run("GetMaxTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMaxTime() // Should return zero value
	})

}

func TestSettersMarkExplicitEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("SetSamples_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueSamples *int

		// Act
		obj.SetSamples(fernTestValueSamples)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSum_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueSum *float64

		// Act
		obj.SetSum(fernTestValueSum)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMin *float64

		// Act
		obj.SetMin(fernTestValueMin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMinTime *int

		// Act
		obj.SetMinTime(fernTestValueMinTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMax_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMax *float64

		// Act
		obj.SetMax(fernTestValueMax)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}
		var fernTestValueMaxTime *int

		// Act
		obj.SetMaxTime(fernTestValueMaxTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("SetSamples", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValue{}
		var fernTestValueSamples *int
		obj.SetSamples(fernTestValueSamples)
		assert.Equal(t, fernTestValueSamples, obj.Samples)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetStats", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValue{}
		var fernTestValueStats *EvolutionResponseDataValuesValueValueStats
		obj.SetStats(fernTestValueStats)
		assert.Equal(t, fernTestValueStats, obj.Stats)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("GetSamples", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		var expected *int
		obj.Samples = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSamples(), "getter should return the property value")
	})

	t.Run("GetSamples_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		obj.Samples = nil

		// Act & Assert
		assert.Nil(t, obj.GetSamples(), "getter should return nil when property is nil")
	})

	t.Run("GetSamples_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSamples() // Should return zero value
	})

	t.Run("GetStats", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		var expected *EvolutionResponseDataValuesValueValueStats
		obj.Stats = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetStats(), "getter should return the property value")
	})

	t.Run("GetStats_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		obj.Stats = nil

		// Act & Assert
		assert.Nil(t, obj.GetStats(), "getter should return nil when property is nil")
	})

	t.Run("GetStats_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValue
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetStats() // Should return zero value
	})

}

func TestSettersMarkExplicitEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("SetSamples_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		var fernTestValueSamples *int

		// Act
		obj.SetSamples(fernTestValueSamples)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetStats_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}
		var fernTestValueStats *EvolutionResponseDataValuesValueValueStats

		// Act
		obj.SetStats(fernTestValueStats)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("SetSum", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueSum *float64
		obj.SetSum(fernTestValueSum)
		assert.Equal(t, fernTestValueSum, obj.Sum)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMin", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMin *float64
		obj.SetMin(fernTestValueMin)
		assert.Equal(t, fernTestValueMin, obj.Min)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMinTime", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMinTime *int
		obj.SetMinTime(fernTestValueMinTime)
		assert.Equal(t, fernTestValueMinTime, obj.MinTime)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMax", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMax *float64
		obj.SetMax(fernTestValueMax)
		assert.Equal(t, fernTestValueMax, obj.Max)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetMaxTime", func(t *testing.T) {
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMaxTime *int
		obj.SetMaxTime(fernTestValueMaxTime)
		assert.Equal(t, fernTestValueMaxTime, obj.MaxTime)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("GetSum", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var expected *float64
		obj.Sum = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSum(), "getter should return the property value")
	})

	t.Run("GetSum_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		obj.Sum = nil

		// Act & Assert
		assert.Nil(t, obj.GetSum(), "getter should return nil when property is nil")
	})

	t.Run("GetSum_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSum() // Should return zero value
	})

	t.Run("GetMin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var expected *float64
		obj.Min = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMin(), "getter should return the property value")
	})

	t.Run("GetMin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		obj.Min = nil

		// Act & Assert
		assert.Nil(t, obj.GetMin(), "getter should return nil when property is nil")
	})

	t.Run("GetMin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMin() // Should return zero value
	})

	t.Run("GetMinTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var expected *int
		obj.MinTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMinTime(), "getter should return the property value")
	})

	t.Run("GetMinTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		obj.MinTime = nil

		// Act & Assert
		assert.Nil(t, obj.GetMinTime(), "getter should return nil when property is nil")
	})

	t.Run("GetMinTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMinTime() // Should return zero value
	})

	t.Run("GetMax", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var expected *float64
		obj.Max = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMax(), "getter should return the property value")
	})

	t.Run("GetMax_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		obj.Max = nil

		// Act & Assert
		assert.Nil(t, obj.GetMax(), "getter should return nil when property is nil")
	})

	t.Run("GetMax_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMax() // Should return zero value
	})

	t.Run("GetMaxTime", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var expected *int
		obj.MaxTime = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMaxTime(), "getter should return the property value")
	})

	t.Run("GetMaxTime_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		obj.MaxTime = nil

		// Act & Assert
		assert.Nil(t, obj.GetMaxTime(), "getter should return nil when property is nil")
	})

	t.Run("GetMaxTime_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMaxTime() // Should return zero value
	})

}

func TestSettersMarkExplicitEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("SetSum_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueSum *float64

		// Act
		obj.SetSum(fernTestValueSum)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMin *float64

		// Act
		obj.SetMin(fernTestValueMin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMinTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMinTime *int

		// Act
		obj.SetMinTime(fernTestValueMinTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMax_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMax *float64

		// Act
		obj.SetMax(fernTestValueMax)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetMaxTime_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}
		var fernTestValueMaxTime *int

		// Act
		obj.SetMaxTime(fernTestValueMaxTime)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingEvolutionResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvolutionResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingEvolutionResponseData(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseData{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvolutionResponseData
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseData
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseData
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataSummaryValue{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvolutionResponseDataSummaryValue
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataSummaryValue
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataSummaryValue
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValue{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvolutionResponseDataValuesValueValue
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataValuesValueValue
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataValuesValueValue
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &EvolutionResponseDataValuesValueValueStats{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled EvolutionResponseDataValuesValueValueStats
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataValuesValueValueStats
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj EvolutionResponseDataValuesValueValueStats
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringEvolutionResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEvolutionResponseData(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseData{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseData
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataSummaryValue{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataValuesValueValue{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValue
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataValuesValueValueStats{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumGetEvolutionDeviceHistoryRequestPeriod(t *testing.T) {
	t.Run("NewFromString_day", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("day")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetEvolutionDeviceHistoryRequestPeriod("day"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_week", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("week")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetEvolutionDeviceHistoryRequestPeriod("week"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_month", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("month")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetEvolutionDeviceHistoryRequestPeriod("month"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_year", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("year")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetEvolutionDeviceHistoryRequestPeriod("year"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewGetEvolutionDeviceHistoryRequestPeriodFromString("day")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesEvolutionResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEvolutionResponseData(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseData{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseData
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEvolutionResponseDataSummaryValue(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataSummaryValue{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataSummaryValue
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEvolutionResponseDataValuesValueValue(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataValuesValueValue{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValue
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesEvolutionResponseDataValuesValueValueStats(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &EvolutionResponseDataValuesValueValueStats{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *EvolutionResponseDataValuesValueValueStats
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
