// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	big "math/big"
)

var (
	getInfoDeviceLiveRequestFieldDeviceID = big.NewInt(1 << 0)
)

type GetInfoDeviceLiveRequest struct {
	DeviceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetInfoDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDeviceID sets the DeviceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetInfoDeviceLiveRequest) SetDeviceID(deviceID string) {
	g.DeviceID = deviceID
	g.require(getInfoDeviceLiveRequestFieldDeviceID)
}

var (
	getOwnerProfileDeviceLiveRequestFieldD = big.NewInt(1 << 0)
)

type GetOwnerProfileDeviceLiveRequest struct {
	D string `json:"d" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetOwnerProfileDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetD sets the D field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetOwnerProfileDeviceLiveRequest) SetD(d string) {
	g.D = d
	g.require(getOwnerProfileDeviceLiveRequestFieldD)
}

func (g *GetOwnerProfileDeviceLiveRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetOwnerProfileDeviceLiveRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetOwnerProfileDeviceLiveRequest(body)
	return nil
}

func (g *GetOwnerProfileDeviceLiveRequest) MarshalJSON() ([]byte, error) {
	type embed GetOwnerProfileDeviceLiveRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getStatsDeviceLiveRequestFieldCode = big.NewInt(1 << 0)
)

type GetStatsDeviceLiveRequest struct {
	Code string `json:"-" url:"code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetStatsDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetStatsDeviceLiveRequest) SetCode(code string) {
	g.Code = code
	g.require(getStatsDeviceLiveRequestFieldCode)
}

var (
	getUpdateStatusDeviceLiveRequestFieldD = big.NewInt(1 << 0)
)

type GetUpdateStatusDeviceLiveRequest struct {
	// Device ID
	D string `json:"d" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetUpdateStatusDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetD sets the D field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUpdateStatusDeviceLiveRequest) SetD(d string) {
	g.D = d
	g.require(getUpdateStatusDeviceLiveRequestFieldD)
}

func (g *GetUpdateStatusDeviceLiveRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUpdateStatusDeviceLiveRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetUpdateStatusDeviceLiveRequest(body)
	return nil
}

func (g *GetUpdateStatusDeviceLiveRequest) MarshalJSON() ([]byte, error) {
	type embed GetUpdateStatusDeviceLiveRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getValuesDeviceLiveRequestFieldDeviceID = big.NewInt(1 << 0)
)

type GetValuesDeviceLiveRequest struct {
	DeviceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetValuesDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDeviceID sets the DeviceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetValuesDeviceLiveRequest) SetDeviceID(deviceID string) {
	g.DeviceID = deviceID
	g.require(getValuesDeviceLiveRequestFieldDeviceID)
}

var (
	getWindRoseDeviceLiveRequestFieldCode = big.NewInt(1 << 0)
)

type GetWindRoseDeviceLiveRequest struct {
	Code string `json:"-" url:"code"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWindRoseDeviceLiveRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWindRoseDeviceLiveRequest) SetCode(code string) {
	g.Code = code
	g.require(getWindRoseDeviceLiveRequestFieldCode)
}

// Station metadata and current sensor snapshot.
// Note: sensor values are returned as strings; unavailable sensors show `-3276.8` / `-32768`.
var (
	deviceInfoFieldDevice = big.NewInt(1 << 0)
	deviceInfoFieldValues = big.NewInt(1 << 1)
)

type DeviceInfo struct {
	Device *DeviceInfoDevice `json:"device,omitempty" url:"device,omitempty"`
	// Current sensor readings as strings.
	// Unavailable sensors return `"-3276.8"` (float sensors) or `"-32768"` (integer sensors).
	Values *DeviceInfoValues `json:"values,omitempty" url:"values,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceInfo) GetDevice() *DeviceInfoDevice {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeviceInfo) GetValues() *DeviceInfoValues {
	if d == nil {
		return nil
	}
	return d.Values
}

func (d *DeviceInfo) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceInfo) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetDevice sets the Device field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfo) SetDevice(device *DeviceInfoDevice) {
	d.Device = device
	d.require(deviceInfoFieldDevice)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfo) SetValues(values *DeviceInfoValues) {
	d.Values = values
	d.require(deviceInfoFieldValues)
}

func (d *DeviceInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceInfo) MarshalJSON() ([]byte, error) {
	type embed DeviceInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceInfo) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceInfoDeviceFieldAccount  = big.NewInt(1 << 0)
	deviceInfoDeviceFieldStatus   = big.NewInt(1 << 1)
	deviceInfoDeviceFieldCity     = big.NewInt(1 << 2)
	deviceInfoDeviceFieldAltitude = big.NewInt(1 << 3)
	deviceInfoDeviceFieldImage    = big.NewInt(1 << 4)
	deviceInfoDeviceFieldIsWebcam = big.NewInt(1 << 5)
	deviceInfoDeviceFieldFavorite = big.NewInt(1 << 6)
	deviceInfoDeviceFieldSocial   = big.NewInt(1 << 7)
	deviceInfoDeviceFieldUpdate   = big.NewInt(1 << 8)
)

type DeviceInfoDevice struct {
	// Account type (0 = free)
	Account *int `json:"account,omitempty" url:"account,omitempty"`
	// "1" = online, "2" = recently online, "3" = offline
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// City name
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// Altitude in metres (as string)
	Altitude *string `json:"altitude,omitempty" url:"altitude,omitempty"`
	// URL to station photo, or null
	Image    *string `json:"image,omitempty" url:"image,omitempty"`
	IsWebcam *bool   `json:"isWebcam,omitempty" url:"isWebcam,omitempty"`
	Favorite *bool   `json:"favorite,omitempty" url:"favorite,omitempty"`
	Social   *bool   `json:"social,omitempty" url:"social,omitempty"`
	// Seconds since last update
	Update *int `json:"update,omitempty" url:"update,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceInfoDevice) GetAccount() *int {
	if d == nil {
		return nil
	}
	return d.Account
}

func (d *DeviceInfoDevice) GetStatus() *string {
	if d == nil {
		return nil
	}
	return d.Status
}

func (d *DeviceInfoDevice) GetCity() *string {
	if d == nil {
		return nil
	}
	return d.City
}

func (d *DeviceInfoDevice) GetAltitude() *string {
	if d == nil {
		return nil
	}
	return d.Altitude
}

func (d *DeviceInfoDevice) GetImage() *string {
	if d == nil {
		return nil
	}
	return d.Image
}

func (d *DeviceInfoDevice) GetIsWebcam() *bool {
	if d == nil {
		return nil
	}
	return d.IsWebcam
}

func (d *DeviceInfoDevice) GetFavorite() *bool {
	if d == nil {
		return nil
	}
	return d.Favorite
}

func (d *DeviceInfoDevice) GetSocial() *bool {
	if d == nil {
		return nil
	}
	return d.Social
}

func (d *DeviceInfoDevice) GetUpdate() *int {
	if d == nil {
		return nil
	}
	return d.Update
}

func (d *DeviceInfoDevice) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceInfoDevice) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetAccount(account *int) {
	d.Account = account
	d.require(deviceInfoDeviceFieldAccount)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetStatus(status *string) {
	d.Status = status
	d.require(deviceInfoDeviceFieldStatus)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetCity(city *string) {
	d.City = city
	d.require(deviceInfoDeviceFieldCity)
}

// SetAltitude sets the Altitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetAltitude(altitude *string) {
	d.Altitude = altitude
	d.require(deviceInfoDeviceFieldAltitude)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetImage(image *string) {
	d.Image = image
	d.require(deviceInfoDeviceFieldImage)
}

// SetIsWebcam sets the IsWebcam field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetIsWebcam(isWebcam *bool) {
	d.IsWebcam = isWebcam
	d.require(deviceInfoDeviceFieldIsWebcam)
}

// SetFavorite sets the Favorite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetFavorite(favorite *bool) {
	d.Favorite = favorite
	d.require(deviceInfoDeviceFieldFavorite)
}

// SetSocial sets the Social field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetSocial(social *bool) {
	d.Social = social
	d.require(deviceInfoDeviceFieldSocial)
}

// SetUpdate sets the Update field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoDevice) SetUpdate(update *int) {
	d.Update = update
	d.require(deviceInfoDeviceFieldUpdate)
}

func (d *DeviceInfoDevice) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceInfoDevice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceInfoDevice(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceInfoDevice) MarshalJSON() ([]byte, error) {
	type embed DeviceInfoDevice
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceInfoDevice) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Current sensor readings as strings.
// Unavailable sensors return `"-3276.8"` (float sensors) or `"-32768"` (integer sensors).
var (
	deviceInfoValuesFieldTemp     = big.NewInt(1 << 0)
	deviceInfoValuesFieldHum      = big.NewInt(1 << 1)
	deviceInfoValuesFieldDew      = big.NewInt(1 << 2)
	deviceInfoValuesFieldWspdavg  = big.NewInt(1 << 3)
	deviceInfoValuesFieldWdiravg  = big.NewInt(1 << 4)
	deviceInfoValuesFieldBar      = big.NewInt(1 << 5)
	deviceInfoValuesFieldRain     = big.NewInt(1 << 6)
	deviceInfoValuesFieldRainrate = big.NewInt(1 << 7)
	deviceInfoValuesFieldSolarrad = big.NewInt(1 << 8)
	deviceInfoValuesFieldUvi      = big.NewInt(1 << 9)
)

type DeviceInfoValues struct {
	// Temperature (°C)
	Temp *string `json:"temp,omitempty" url:"temp,omitempty"`
	// Relative humidity (%)
	Hum *string `json:"hum,omitempty" url:"hum,omitempty"`
	// Dew point (°C)
	Dew *string `json:"dew,omitempty" url:"dew,omitempty"`
	// Average wind speed (m/s)
	Wspdavg *string `json:"wspdavg,omitempty" url:"wspdavg,omitempty"`
	// Average wind direction (°)
	Wdiravg *string `json:"wdiravg,omitempty" url:"wdiravg,omitempty"`
	// Barometric pressure (hPa)
	Bar *string `json:"bar,omitempty" url:"bar,omitempty"`
	// Total rain (mm)
	Rain *string `json:"rain,omitempty" url:"rain,omitempty"`
	// Rain rate (mm/h)
	Rainrate *string `json:"rainrate,omitempty" url:"rainrate,omitempty"`
	// Solar radiation (W/m²)
	Solarrad *string `json:"solarrad,omitempty" url:"solarrad,omitempty"`
	// UV index
	Uvi *string `json:"uvi,omitempty" url:"uvi,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceInfoValues) GetTemp() *string {
	if d == nil {
		return nil
	}
	return d.Temp
}

func (d *DeviceInfoValues) GetHum() *string {
	if d == nil {
		return nil
	}
	return d.Hum
}

func (d *DeviceInfoValues) GetDew() *string {
	if d == nil {
		return nil
	}
	return d.Dew
}

func (d *DeviceInfoValues) GetWspdavg() *string {
	if d == nil {
		return nil
	}
	return d.Wspdavg
}

func (d *DeviceInfoValues) GetWdiravg() *string {
	if d == nil {
		return nil
	}
	return d.Wdiravg
}

func (d *DeviceInfoValues) GetBar() *string {
	if d == nil {
		return nil
	}
	return d.Bar
}

func (d *DeviceInfoValues) GetRain() *string {
	if d == nil {
		return nil
	}
	return d.Rain
}

func (d *DeviceInfoValues) GetRainrate() *string {
	if d == nil {
		return nil
	}
	return d.Rainrate
}

func (d *DeviceInfoValues) GetSolarrad() *string {
	if d == nil {
		return nil
	}
	return d.Solarrad
}

func (d *DeviceInfoValues) GetUvi() *string {
	if d == nil {
		return nil
	}
	return d.Uvi
}

func (d *DeviceInfoValues) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceInfoValues) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetTemp sets the Temp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetTemp(temp *string) {
	d.Temp = temp
	d.require(deviceInfoValuesFieldTemp)
}

// SetHum sets the Hum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetHum(hum *string) {
	d.Hum = hum
	d.require(deviceInfoValuesFieldHum)
}

// SetDew sets the Dew field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetDew(dew *string) {
	d.Dew = dew
	d.require(deviceInfoValuesFieldDew)
}

// SetWspdavg sets the Wspdavg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetWspdavg(wspdavg *string) {
	d.Wspdavg = wspdavg
	d.require(deviceInfoValuesFieldWspdavg)
}

// SetWdiravg sets the Wdiravg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetWdiravg(wdiravg *string) {
	d.Wdiravg = wdiravg
	d.require(deviceInfoValuesFieldWdiravg)
}

// SetBar sets the Bar field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetBar(bar *string) {
	d.Bar = bar
	d.require(deviceInfoValuesFieldBar)
}

// SetRain sets the Rain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetRain(rain *string) {
	d.Rain = rain
	d.require(deviceInfoValuesFieldRain)
}

// SetRainrate sets the Rainrate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetRainrate(rainrate *string) {
	d.Rainrate = rainrate
	d.require(deviceInfoValuesFieldRainrate)
}

// SetSolarrad sets the Solarrad field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetSolarrad(solarrad *string) {
	d.Solarrad = solarrad
	d.require(deviceInfoValuesFieldSolarrad)
}

// SetUvi sets the Uvi field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceInfoValues) SetUvi(uvi *string) {
	d.Uvi = uvi
	d.require(deviceInfoValuesFieldUvi)
}

func (d *DeviceInfoValues) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceInfoValues
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceInfoValues(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceInfoValues) MarshalJSON() ([]byte, error) {
	type embed DeviceInfoValues
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceInfoValues) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceProfileFieldObserver  = big.NewInt(1 << 0)
	deviceProfileFieldFollowers = big.NewInt(1 << 1)
	deviceProfileFieldDevice    = big.NewInt(1 << 2)
)

type DeviceProfile struct {
	Observer  *DeviceProfileObserver  `json:"observer,omitempty" url:"observer,omitempty"`
	Followers *DeviceProfileFollowers `json:"followers,omitempty" url:"followers,omitempty"`
	Device    *DeviceProfileDevice    `json:"device,omitempty" url:"device,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceProfile) GetObserver() *DeviceProfileObserver {
	if d == nil {
		return nil
	}
	return d.Observer
}

func (d *DeviceProfile) GetFollowers() *DeviceProfileFollowers {
	if d == nil {
		return nil
	}
	return d.Followers
}

func (d *DeviceProfile) GetDevice() *DeviceProfileDevice {
	if d == nil {
		return nil
	}
	return d.Device
}

func (d *DeviceProfile) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceProfile) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetObserver sets the Observer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfile) SetObserver(observer *DeviceProfileObserver) {
	d.Observer = observer
	d.require(deviceProfileFieldObserver)
}

// SetFollowers sets the Followers field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfile) SetFollowers(followers *DeviceProfileFollowers) {
	d.Followers = followers
	d.require(deviceProfileFieldFollowers)
}

// SetDevice sets the Device field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfile) SetDevice(device *DeviceProfileDevice) {
	d.Device = device
	d.require(deviceProfileFieldDevice)
}

func (d *DeviceProfile) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceProfile
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceProfile(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceProfile) MarshalJSON() ([]byte, error) {
	type embed DeviceProfile
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceProfile) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceProfileDeviceFieldBrand = big.NewInt(1 << 0)
	deviceProfileDeviceFieldModel = big.NewInt(1 << 1)
)

type DeviceProfileDevice struct {
	Brand *string `json:"brand,omitempty" url:"brand,omitempty"`
	Model *string `json:"model,omitempty" url:"model,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceProfileDevice) GetBrand() *string {
	if d == nil {
		return nil
	}
	return d.Brand
}

func (d *DeviceProfileDevice) GetModel() *string {
	if d == nil {
		return nil
	}
	return d.Model
}

func (d *DeviceProfileDevice) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceProfileDevice) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetBrand sets the Brand field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileDevice) SetBrand(brand *string) {
	d.Brand = brand
	d.require(deviceProfileDeviceFieldBrand)
}

// SetModel sets the Model field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileDevice) SetModel(model *string) {
	d.Model = model
	d.require(deviceProfileDeviceFieldModel)
}

func (d *DeviceProfileDevice) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceProfileDevice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceProfileDevice(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceProfileDevice) MarshalJSON() ([]byte, error) {
	type embed DeviceProfileDevice
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceProfileDevice) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceProfileFollowersFieldNumber = big.NewInt(1 << 0)
)

type DeviceProfileFollowers struct {
	Number *string `json:"number,omitempty" url:"number,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceProfileFollowers) GetNumber() *string {
	if d == nil {
		return nil
	}
	return d.Number
}

func (d *DeviceProfileFollowers) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceProfileFollowers) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetNumber sets the Number field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileFollowers) SetNumber(number *string) {
	d.Number = number
	d.require(deviceProfileFollowersFieldNumber)
}

func (d *DeviceProfileFollowers) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceProfileFollowers
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceProfileFollowers(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceProfileFollowers) MarshalJSON() ([]byte, error) {
	type embed DeviceProfileFollowers
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceProfileFollowers) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	deviceProfileObserverFieldName     = big.NewInt(1 << 0)
	deviceProfileObserverFieldNickname = big.NewInt(1 << 1)
	deviceProfileObserverFieldCompany  = big.NewInt(1 << 2)
)

type DeviceProfileObserver struct {
	Name     *string `json:"name,omitempty" url:"name,omitempty"`
	Nickname *string `json:"nickname,omitempty" url:"nickname,omitempty"`
	Company  *string `json:"company,omitempty" url:"company,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceProfileObserver) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DeviceProfileObserver) GetNickname() *string {
	if d == nil {
		return nil
	}
	return d.Nickname
}

func (d *DeviceProfileObserver) GetCompany() *string {
	if d == nil {
		return nil
	}
	return d.Company
}

func (d *DeviceProfileObserver) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceProfileObserver) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileObserver) SetName(name *string) {
	d.Name = name
	d.require(deviceProfileObserverFieldName)
}

// SetNickname sets the Nickname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileObserver) SetNickname(nickname *string) {
	d.Nickname = nickname
	d.require(deviceProfileObserverFieldNickname)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceProfileObserver) SetCompany(company *string) {
	d.Company = company
	d.require(deviceProfileObserverFieldCompany)
}

func (d *DeviceProfileObserver) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceProfileObserver
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceProfileObserver(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceProfileObserver) MarshalJSON() ([]byte, error) {
	type embed DeviceProfileObserver
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceProfileObserver) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// Current readings and period statistics for all sensors.
// All values are `[unix_timestamp, value]` tuples (`TimestampValue`).
//
// **Key pattern:** `{sensor}_{period}_{type}`
// - Sensors: `temp`, `tempin`, `dew`, `chill`, `heat`, `heatin`, `hum`, `humin`, `bar`, `wdir`, `wdiravg`, `wspd`, `wspdavg`, `wspdhi`, `rainrate`, `rain`, `solarrad`, `uvi`
// - Period types: `current`, `day_max`, `day_min`, `month_max`, `month_min`, `year_max`, `year_min`
// - Rain also has: `day_total`, `month_total`, `year_total`
// - Solarrad also has: `day_hours`, `month_hours`, `year_hours`
var (
	deviceStatsFieldLastUpdate = big.NewInt(1 << 0)
)

type DeviceStats struct {
	// Unix timestamp of last reading
	LastUpdate *int `json:"last_update,omitempty" url:"last_update,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceStats) GetLastUpdate() *int {
	if d == nil {
		return nil
	}
	return d.LastUpdate
}

func (d *DeviceStats) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceStats) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetLastUpdate sets the LastUpdate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceStats) SetLastUpdate(lastUpdate *int) {
	d.LastUpdate = lastUpdate
	d.require(deviceStatsFieldLastUpdate)
}

func (d *DeviceStats) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceStats
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceStats(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceStats) MarshalJSON() ([]byte, error) {
	type embed DeviceStats
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceStats) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	windDataFieldDate   = big.NewInt(1 << 0)
	windDataFieldValues = big.NewInt(1 << 1)
)

type WindData struct {
	// Unix timestamp (start of period)
	Date *int `json:"date,omitempty" url:"date,omitempty"`
	// 16 compass directions, each with sum and scale array
	Values []*WindDataValuesItem `json:"values,omitempty" url:"values,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WindData) GetDate() *int {
	if w == nil {
		return nil
	}
	return w.Date
}

func (w *WindData) GetValues() []*WindDataValuesItem {
	if w == nil {
		return nil
	}
	return w.Values
}

func (w *WindData) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WindData) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WindData) SetDate(date *int) {
	w.Date = date
	w.require(windDataFieldDate)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WindData) SetValues(values []*WindDataValuesItem) {
	w.Values = values
	w.require(windDataFieldValues)
}

func (w *WindData) UnmarshalJSON(data []byte) error {
	type unmarshaler WindData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WindData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WindData) MarshalJSON() ([]byte, error) {
	type embed WindData
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WindData) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	windDataValuesItemFieldSum   = big.NewInt(1 << 0)
	windDataValuesItemFieldScale = big.NewInt(1 << 1)
)

type WindDataValuesItem struct {
	Sum   *float64 `json:"sum,omitempty" url:"sum,omitempty"`
	Scale []int    `json:"scale,omitempty" url:"scale,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (w *WindDataValuesItem) GetSum() *float64 {
	if w == nil {
		return nil
	}
	return w.Sum
}

func (w *WindDataValuesItem) GetScale() []int {
	if w == nil {
		return nil
	}
	return w.Scale
}

func (w *WindDataValuesItem) GetExtraProperties() map[string]interface{} {
	if w == nil {
		return nil
	}
	return w.extraProperties
}

func (w *WindDataValuesItem) require(field *big.Int) {
	if w.explicitFields == nil {
		w.explicitFields = big.NewInt(0)
	}
	w.explicitFields.Or(w.explicitFields, field)
}

// SetSum sets the Sum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WindDataValuesItem) SetSum(sum *float64) {
	w.Sum = sum
	w.require(windDataValuesItemFieldSum)
}

// SetScale sets the Scale field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (w *WindDataValuesItem) SetScale(scale []int) {
	w.Scale = scale
	w.require(windDataValuesItemFieldScale)
}

func (w *WindDataValuesItem) UnmarshalJSON(data []byte) error {
	type unmarshaler WindDataValuesItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*w = WindDataValuesItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *w)
	if err != nil {
		return err
	}
	w.extraProperties = extraProperties
	w.rawJSON = json.RawMessage(data)
	return nil
}

func (w *WindDataValuesItem) MarshalJSON() ([]byte, error) {
	type embed WindDataValuesItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*w),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, w.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (w *WindDataValuesItem) String() string {
	if w == nil {
		return "<nil>"
	}
	if len(w.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(w.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

var (
	getUpdateStatusDeviceLiveResponseFieldUpdate     = big.NewInt(1 << 0)
	getUpdateStatusDeviceLiveResponseFieldStatus     = big.NewInt(1 << 1)
	getUpdateStatusDeviceLiveResponseFieldServerTime = big.NewInt(1 << 2)
)

type GetUpdateStatusDeviceLiveResponse struct {
	// Seconds since last update
	Update *int `json:"update,omitempty" url:"update,omitempty"`
	// "1" = online, "2" = recently online, "3" = offline
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Current server Unix timestamp
	ServerTime *int `json:"server_time,omitempty" url:"server_time,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetUpdateStatusDeviceLiveResponse) GetUpdate() *int {
	if g == nil {
		return nil
	}
	return g.Update
}

func (g *GetUpdateStatusDeviceLiveResponse) GetStatus() *string {
	if g == nil {
		return nil
	}
	return g.Status
}

func (g *GetUpdateStatusDeviceLiveResponse) GetServerTime() *int {
	if g == nil {
		return nil
	}
	return g.ServerTime
}

func (g *GetUpdateStatusDeviceLiveResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetUpdateStatusDeviceLiveResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUpdate sets the Update field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUpdateStatusDeviceLiveResponse) SetUpdate(update *int) {
	g.Update = update
	g.require(getUpdateStatusDeviceLiveResponseFieldUpdate)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUpdateStatusDeviceLiveResponse) SetStatus(status *string) {
	g.Status = status
	g.require(getUpdateStatusDeviceLiveResponseFieldStatus)
}

// SetServerTime sets the ServerTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetUpdateStatusDeviceLiveResponse) SetServerTime(serverTime *int) {
	g.ServerTime = serverTime
	g.require(getUpdateStatusDeviceLiveResponseFieldServerTime)
}

func (g *GetUpdateStatusDeviceLiveResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetUpdateStatusDeviceLiveResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetUpdateStatusDeviceLiveResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetUpdateStatusDeviceLiveResponse) MarshalJSON() ([]byte, error) {
	type embed GetUpdateStatusDeviceLiveResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetUpdateStatusDeviceLiveResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
