// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	big "math/big"
)

var (
	getDailyForecastRequestFieldID = big.NewInt(1 << 0)
)

type GetDailyForecastRequest struct {
	ID string `json:"-" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDailyForecastRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDailyForecastRequest) SetID(id string) {
	g.ID = id
	g.require(getDailyForecastRequestFieldID)
}

var (
	forecastResponseFieldInfo     = big.NewInt(1 << 0)
	forecastResponseFieldLocation = big.NewInt(1 << 1)
	forecastResponseFieldForecast = big.NewInt(1 << 2)
)

type ForecastResponse struct {
	Info     *ForecastResponseInfo     `json:"info,omitempty" url:"info,omitempty"`
	Location *ForecastResponseLocation `json:"location,omitempty" url:"location,omitempty"`
	// Keyed by date string (YYYY-MM-DD)
	Forecast map[string]*ForecastResponseForecastValue `json:"forecast,omitempty" url:"forecast,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponse) GetInfo() *ForecastResponseInfo {
	if f == nil {
		return nil
	}
	return f.Info
}

func (f *ForecastResponse) GetLocation() *ForecastResponseLocation {
	if f == nil {
		return nil
	}
	return f.Location
}

func (f *ForecastResponse) GetForecast() map[string]*ForecastResponseForecastValue {
	if f == nil {
		return nil
	}
	return f.Forecast
}

func (f *ForecastResponse) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponse) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetInfo sets the Info field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponse) SetInfo(info *ForecastResponseInfo) {
	f.Info = info
	f.require(forecastResponseFieldInfo)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponse) SetLocation(location *ForecastResponseLocation) {
	f.Location = location
	f.require(forecastResponseFieldLocation)
}

// SetForecast sets the Forecast field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponse) SetForecast(forecast map[string]*ForecastResponseForecastValue) {
	f.Forecast = forecast
	f.require(forecastResponseFieldForecast)
}

func (f *ForecastResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponse) MarshalJSON() ([]byte, error) {
	type embed ForecastResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponse) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forecastResponseForecastValueFieldWeather     = big.NewInt(1 << 0)
	forecastResponseForecastValueFieldTemperature = big.NewInt(1 << 1)
)

type ForecastResponseForecastValue struct {
	Weather     *ForecastResponseForecastValueWeather     `json:"weather,omitempty" url:"weather,omitempty"`
	Temperature *ForecastResponseForecastValueTemperature `json:"temperature,omitempty" url:"temperature,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponseForecastValue) GetWeather() *ForecastResponseForecastValueWeather {
	if f == nil {
		return nil
	}
	return f.Weather
}

func (f *ForecastResponseForecastValue) GetTemperature() *ForecastResponseForecastValueTemperature {
	if f == nil {
		return nil
	}
	return f.Temperature
}

func (f *ForecastResponseForecastValue) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponseForecastValue) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetWeather sets the Weather field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseForecastValue) SetWeather(weather *ForecastResponseForecastValueWeather) {
	f.Weather = weather
	f.require(forecastResponseForecastValueFieldWeather)
}

// SetTemperature sets the Temperature field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseForecastValue) SetTemperature(temperature *ForecastResponseForecastValueTemperature) {
	f.Temperature = temperature
	f.require(forecastResponseForecastValueFieldTemperature)
}

func (f *ForecastResponseForecastValue) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponseForecastValue
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponseForecastValue(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponseForecastValue) MarshalJSON() ([]byte, error) {
	type embed ForecastResponseForecastValue
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponseForecastValue) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forecastResponseForecastValueTemperatureFieldMax = big.NewInt(1 << 0)
	forecastResponseForecastValueTemperatureFieldMin = big.NewInt(1 << 1)
)

type ForecastResponseForecastValueTemperature struct {
	Max *int `json:"max,omitempty" url:"max,omitempty"`
	Min *int `json:"min,omitempty" url:"min,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponseForecastValueTemperature) GetMax() *int {
	if f == nil {
		return nil
	}
	return f.Max
}

func (f *ForecastResponseForecastValueTemperature) GetMin() *int {
	if f == nil {
		return nil
	}
	return f.Min
}

func (f *ForecastResponseForecastValueTemperature) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponseForecastValueTemperature) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetMax sets the Max field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseForecastValueTemperature) SetMax(max *int) {
	f.Max = max
	f.require(forecastResponseForecastValueTemperatureFieldMax)
}

// SetMin sets the Min field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseForecastValueTemperature) SetMin(min *int) {
	f.Min = min
	f.require(forecastResponseForecastValueTemperatureFieldMin)
}

func (f *ForecastResponseForecastValueTemperature) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponseForecastValueTemperature
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponseForecastValueTemperature(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponseForecastValueTemperature) MarshalJSON() ([]byte, error) {
	type embed ForecastResponseForecastValueTemperature
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponseForecastValueTemperature) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forecastResponseForecastValueWeatherFieldCode = big.NewInt(1 << 0)
)

type ForecastResponseForecastValueWeather struct {
	// WMO weather interpretation code
	Code *int `json:"code,omitempty" url:"code,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponseForecastValueWeather) GetCode() *int {
	if f == nil {
		return nil
	}
	return f.Code
}

func (f *ForecastResponseForecastValueWeather) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponseForecastValueWeather) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseForecastValueWeather) SetCode(code *int) {
	f.Code = code
	f.require(forecastResponseForecastValueWeatherFieldCode)
}

func (f *ForecastResponseForecastValueWeather) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponseForecastValueWeather
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponseForecastValueWeather(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponseForecastValueWeather) MarshalJSON() ([]byte, error) {
	type embed ForecastResponseForecastValueWeather
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponseForecastValueWeather) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forecastResponseInfoFieldSource = big.NewInt(1 << 0)
	forecastResponseInfoFieldWeb    = big.NewInt(1 << 1)
	forecastResponseInfoFieldDays   = big.NewInt(1 << 2)
)

type ForecastResponseInfo struct {
	Source *string `json:"source,omitempty" url:"source,omitempty"`
	Web    *string `json:"web,omitempty" url:"web,omitempty"`
	Days   *int    `json:"days,omitempty" url:"days,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponseInfo) GetSource() *string {
	if f == nil {
		return nil
	}
	return f.Source
}

func (f *ForecastResponseInfo) GetWeb() *string {
	if f == nil {
		return nil
	}
	return f.Web
}

func (f *ForecastResponseInfo) GetDays() *int {
	if f == nil {
		return nil
	}
	return f.Days
}

func (f *ForecastResponseInfo) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponseInfo) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetSource sets the Source field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseInfo) SetSource(source *string) {
	f.Source = source
	f.require(forecastResponseInfoFieldSource)
}

// SetWeb sets the Web field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseInfo) SetWeb(web *string) {
	f.Web = web
	f.require(forecastResponseInfoFieldWeb)
}

// SetDays sets the Days field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseInfo) SetDays(days *int) {
	f.Days = days
	f.require(forecastResponseInfoFieldDays)
}

func (f *ForecastResponseInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponseInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponseInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponseInfo) MarshalJSON() ([]byte, error) {
	type embed ForecastResponseInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponseInfo) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

var (
	forecastResponseLocationFieldName = big.NewInt(1 << 0)
)

type ForecastResponseLocation struct {
	// Nearest city name
	Name *string `json:"name,omitempty" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (f *ForecastResponseLocation) GetName() *string {
	if f == nil {
		return nil
	}
	return f.Name
}

func (f *ForecastResponseLocation) GetExtraProperties() map[string]interface{} {
	if f == nil {
		return nil
	}
	return f.extraProperties
}

func (f *ForecastResponseLocation) require(field *big.Int) {
	if f.explicitFields == nil {
		f.explicitFields = big.NewInt(0)
	}
	f.explicitFields.Or(f.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (f *ForecastResponseLocation) SetName(name *string) {
	f.Name = name
	f.require(forecastResponseLocationFieldName)
}

func (f *ForecastResponseLocation) UnmarshalJSON(data []byte) error {
	type unmarshaler ForecastResponseLocation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*f = ForecastResponseLocation(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *f)
	if err != nil {
		return err
	}
	f.extraProperties = extraProperties
	f.rawJSON = json.RawMessage(data)
	return nil
}

func (f *ForecastResponseLocation) MarshalJSON() ([]byte, error) {
	type embed ForecastResponseLocation
	var marshaler = struct {
		embed
	}{
		embed: embed(*f),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, f.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (f *ForecastResponseLocation) String() string {
	if f == nil {
		return "<nil>"
	}
	if len(f.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(f.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}
