// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

var (
	getBackgroundDevicesMapRequestFieldUser = big.NewInt(1 << 0)
)

type GetBackgroundDevicesMapRequest struct {
	User *string `json:"user,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetBackgroundDevicesMapRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetBackgroundDevicesMapRequest) SetUser(user *string) {
	g.User = user
	g.require(getBackgroundDevicesMapRequestFieldUser)
}

func (g *GetBackgroundDevicesMapRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetBackgroundDevicesMapRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetBackgroundDevicesMapRequest(body)
	return nil
}

func (g *GetBackgroundDevicesMapRequest) MarshalJSON() ([]byte, error) {
	type embed GetBackgroundDevicesMapRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getDevicesMapRequestFieldUser     = big.NewInt(1 << 0)
	getDevicesMapRequestFieldLocation = big.NewInt(1 << 1)
)

type GetDevicesMapRequest struct {
	// Filter by user (empty = all)
	User *string `json:"user,omitempty" url:"-"`
	// lat,lon,zoom format
	Location *string `json:"location,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDevicesMapRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUser sets the User field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDevicesMapRequest) SetUser(user *string) {
	g.User = user
	g.require(getDevicesMapRequestFieldUser)
}

// SetLocation sets the Location field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDevicesMapRequest) SetLocation(location *string) {
	g.Location = location
	g.require(getDevicesMapRequestFieldLocation)
}

func (g *GetDevicesMapRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDevicesMapRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetDevicesMapRequest(body)
	return nil
}

func (g *GetDevicesMapRequest) MarshalJSON() ([]byte, error) {
	type embed GetDevicesMapRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Stations as compact arrays. Also contains `owner` and `favorites` arrays (empty unless logged in).
var (
	mapDevicesResponseFieldDevices   = big.NewInt(1 << 0)
	mapDevicesResponseFieldOwner     = big.NewInt(1 << 1)
	mapDevicesResponseFieldFavorites = big.NewInt(1 << 2)
)

type MapDevicesResponse struct {
	// Each entry is an array:
	// `[id, city, lat, lon, status, 0, temp×10, hum, bar×10, wspd×10, wdir, rainrate×10, rain×10, solarrad×10, uvi×10]`
	//
	// - `status`: 1=online, 2=recently online, 3=offline
	// - Divide index 6 and above by 10 to get real units
	Devices [][]any `json:"devices,omitempty" url:"devices,omitempty"`
	// Owner's own stations (empty if not logged in)
	Owner [][]any `json:"owner,omitempty" url:"owner,omitempty"`
	// Favourite stations (empty if not logged in)
	Favorites [][]any `json:"favorites,omitempty" url:"favorites,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MapDevicesResponse) GetDevices() [][]any {
	if m == nil {
		return nil
	}
	return m.Devices
}

func (m *MapDevicesResponse) GetOwner() [][]any {
	if m == nil {
		return nil
	}
	return m.Owner
}

func (m *MapDevicesResponse) GetFavorites() [][]any {
	if m == nil {
		return nil
	}
	return m.Favorites
}

func (m *MapDevicesResponse) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MapDevicesResponse) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetDevices sets the Devices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MapDevicesResponse) SetDevices(devices [][]any) {
	m.Devices = devices
	m.require(mapDevicesResponseFieldDevices)
}

// SetOwner sets the Owner field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MapDevicesResponse) SetOwner(owner [][]any) {
	m.Owner = owner
	m.require(mapDevicesResponseFieldOwner)
}

// SetFavorites sets the Favorites field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MapDevicesResponse) SetFavorites(favorites [][]any) {
	m.Favorites = favorites
	m.require(mapDevicesResponseFieldFavorites)
}

func (m *MapDevicesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler MapDevicesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MapDevicesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MapDevicesResponse) MarshalJSON() ([]byte, error) {
	type embed MapDevicesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MapDevicesResponse) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	getMetarsMapResponseFieldMetars = big.NewInt(1 << 0)
)

type GetMetarsMapResponse struct {
	// Each entry: `[icao, city, lat, lon, status, 0, wdir, hum, bar*10, wspd*10, wdir2, 0, "", "", ""]`
	Metars [][]any `json:"metars,omitempty" url:"metars,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMetarsMapResponse) GetMetars() [][]any {
	if g == nil {
		return nil
	}
	return g.Metars
}

func (g *GetMetarsMapResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetMetarsMapResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetMetars sets the Metars field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMetarsMapResponse) SetMetars(metars [][]any) {
	g.Metars = metars
	g.require(getMetarsMapResponseFieldMetars)
}

func (g *GetMetarsMapResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMetarsMapResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMetarsMapResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMetarsMapResponse) MarshalJSON() ([]byte, error) {
	type embed GetMetarsMapResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMetarsMapResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
