// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetBackgroundDevicesMapRequest(t *testing.T) {
	t.Run("SetUser", func(t *testing.T) {
		obj := &GetBackgroundDevicesMapRequest{}
		var fernTestValueUser *string
		obj.SetUser(fernTestValueUser)
		assert.Equal(t, fernTestValueUser, obj.User)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetBackgroundDevicesMapRequest(t *testing.T) {
	t.Run("SetUser_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetBackgroundDevicesMapRequest{}
		var fernTestValueUser *string

		// Act
		obj.SetUser(fernTestValueUser)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetDevicesMapRequest(t *testing.T) {
	t.Run("SetUser", func(t *testing.T) {
		obj := &GetDevicesMapRequest{}
		var fernTestValueUser *string
		obj.SetUser(fernTestValueUser)
		assert.Equal(t, fernTestValueUser, obj.User)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLocation", func(t *testing.T) {
		obj := &GetDevicesMapRequest{}
		var fernTestValueLocation *string
		obj.SetLocation(fernTestValueLocation)
		assert.Equal(t, fernTestValueLocation, obj.Location)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetDevicesMapRequest(t *testing.T) {
	t.Run("SetUser_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetDevicesMapRequest{}
		var fernTestValueUser *string

		// Act
		obj.SetUser(fernTestValueUser)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLocation_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetDevicesMapRequest{}
		var fernTestValueLocation *string

		// Act
		obj.SetLocation(fernTestValueLocation)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersMapDevicesResponse(t *testing.T) {
	t.Run("SetDevices", func(t *testing.T) {
		obj := &MapDevicesResponse{}
		var fernTestValueDevices [][]any
		obj.SetDevices(fernTestValueDevices)
		assert.Equal(t, fernTestValueDevices, obj.Devices)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOwner", func(t *testing.T) {
		obj := &MapDevicesResponse{}
		var fernTestValueOwner [][]any
		obj.SetOwner(fernTestValueOwner)
		assert.Equal(t, fernTestValueOwner, obj.Owner)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFavorites", func(t *testing.T) {
		obj := &MapDevicesResponse{}
		var fernTestValueFavorites [][]any
		obj.SetFavorites(fernTestValueFavorites)
		assert.Equal(t, fernTestValueFavorites, obj.Favorites)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersMapDevicesResponse(t *testing.T) {
	t.Run("GetDevices", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var expected [][]any
		obj.Devices = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDevices(), "getter should return the property value")
	})

	t.Run("GetDevices_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		obj.Devices = nil

		// Act & Assert
		assert.Nil(t, obj.GetDevices(), "getter should return nil when property is nil")
	})

	t.Run("GetDevices_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MapDevicesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDevices() // Should return zero value
	})

	t.Run("GetOwner", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var expected [][]any
		obj.Owner = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOwner(), "getter should return the property value")
	})

	t.Run("GetOwner_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		obj.Owner = nil

		// Act & Assert
		assert.Nil(t, obj.GetOwner(), "getter should return nil when property is nil")
	})

	t.Run("GetOwner_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MapDevicesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOwner() // Should return zero value
	})

	t.Run("GetFavorites", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var expected [][]any
		obj.Favorites = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFavorites(), "getter should return the property value")
	})

	t.Run("GetFavorites_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		obj.Favorites = nil

		// Act & Assert
		assert.Nil(t, obj.GetFavorites(), "getter should return nil when property is nil")
	})

	t.Run("GetFavorites_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MapDevicesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFavorites() // Should return zero value
	})

}

func TestSettersMarkExplicitMapDevicesResponse(t *testing.T) {
	t.Run("SetDevices_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var fernTestValueDevices [][]any

		// Act
		obj.SetDevices(fernTestValueDevices)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOwner_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var fernTestValueOwner [][]any

		// Act
		obj.SetOwner(fernTestValueOwner)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFavorites_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}
		var fernTestValueFavorites [][]any

		// Act
		obj.SetFavorites(fernTestValueFavorites)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetMetarsMapResponse(t *testing.T) {
	t.Run("SetMetars", func(t *testing.T) {
		obj := &GetMetarsMapResponse{}
		var fernTestValueMetars [][]any
		obj.SetMetars(fernTestValueMetars)
		assert.Equal(t, fernTestValueMetars, obj.Metars)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGetMetarsMapResponse(t *testing.T) {
	t.Run("GetMetars", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMetarsMapResponse{}
		var expected [][]any
		obj.Metars = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetMetars(), "getter should return the property value")
	})

	t.Run("GetMetars_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMetarsMapResponse{}
		obj.Metars = nil

		// Act & Assert
		assert.Nil(t, obj.GetMetars(), "getter should return nil when property is nil")
	})

	t.Run("GetMetars_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMetarsMapResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetMetars() // Should return zero value
	})

}

func TestSettersMarkExplicitGetMetarsMapResponse(t *testing.T) {
	t.Run("SetMetars_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMetarsMapResponse{}
		var fernTestValueMetars [][]any

		// Act
		obj.SetMetars(fernTestValueMetars)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGetMetarsMapResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMetarsMapResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GetMetarsMapResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GetMetarsMapResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GetMetarsMapResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingMapDevicesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &MapDevicesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled MapDevicesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj MapDevicesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj MapDevicesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGetMetarsMapResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GetMetarsMapResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMetarsMapResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringMapDevicesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &MapDevicesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MapDevicesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesGetMetarsMapResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GetMetarsMapResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GetMetarsMapResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesMapDevicesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &MapDevicesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *MapDevicesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
