// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	big "math/big"
)

var (
	getValuesMetarRequestFieldDeviceID = big.NewInt(1 << 0)
)

type GetValuesMetarRequest struct {
	// ICAO airport code
	DeviceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetValuesMetarRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDeviceID sets the DeviceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetValuesMetarRequest) SetDeviceID(deviceID string) {
	g.DeviceID = deviceID
	g.require(getValuesMetarRequestFieldDeviceID)
}
