// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	big "math/big"
)

var (
	getMostFollowedStationsRequestFieldCountry = big.NewInt(1 << 0)
)

type GetMostFollowedStationsRequest struct {
	Country string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetMostFollowedStationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMostFollowedStationsRequest) SetCountry(country string) {
	g.Country = country
	g.require(getMostFollowedStationsRequestFieldCountry)
}

var (
	getNearbyStationsRequestFieldLat = big.NewInt(1 << 0)
	getNearbyStationsRequestFieldLon = big.NewInt(1 << 1)
	getNearbyStationsRequestFieldKm  = big.NewInt(1 << 2)
)

type GetNearbyStationsRequest struct {
	Lat float64 `json:"-" url:"-"`
	Lon float64 `json:"-" url:"-"`
	Km  int     `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNearbyStationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLat sets the Lat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNearbyStationsRequest) SetLat(lat float64) {
	g.Lat = lat
	g.require(getNearbyStationsRequestFieldLat)
}

// SetLon sets the Lon field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNearbyStationsRequest) SetLon(lon float64) {
	g.Lon = lon
	g.require(getNearbyStationsRequestFieldLon)
}

// SetKm sets the Km field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNearbyStationsRequest) SetKm(km int) {
	g.Km = km
	g.require(getNearbyStationsRequestFieldKm)
}

var (
	getNewestStationsRequestFieldCountry = big.NewInt(1 << 0)
)

type GetNewestStationsRequest struct {
	Country string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetNewestStationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetNewestStationsRequest) SetCountry(country string) {
	g.Country = country
	g.require(getNewestStationsRequestFieldCountry)
}

var (
	getPopularStationsRequestFieldCountry = big.NewInt(1 << 0)
	getPopularStationsRequestFieldPeriod  = big.NewInt(1 << 1)
)

type GetPopularStationsRequest struct {
	Country string                          `json:"-" url:"-"`
	Period  GetPopularStationsRequestPeriod `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetPopularStationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPopularStationsRequest) SetCountry(country string) {
	g.Country = country
	g.require(getPopularStationsRequestFieldCountry)
}

// SetPeriod sets the Period field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetPopularStationsRequest) SetPeriod(period GetPopularStationsRequestPeriod) {
	g.Period = period
	g.require(getPopularStationsRequestFieldPeriod)
}

var (
	getStationPageStationsRequestFieldDeviceID = big.NewInt(1 << 0)
)

type GetStationPageStationsRequest struct {
	DeviceID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetStationPageStationsRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetDeviceID sets the DeviceID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetStationPageStationsRequest) SetDeviceID(deviceID string) {
	g.DeviceID = deviceID
	g.require(getStationPageStationsRequestFieldDeviceID)
}

// Station entry returned by page/coordinates
var (
	pageDeviceFieldType       = big.NewInt(1 << 0)
	pageDeviceFieldCode       = big.NewInt(1 << 1)
	pageDeviceFieldName       = big.NewInt(1 << 2)
	pageDeviceFieldCity       = big.NewInt(1 << 3)
	pageDeviceFieldLatitude   = big.NewInt(1 << 4)
	pageDeviceFieldLongitude  = big.NewInt(1 << 5)
	pageDeviceFieldElevation  = big.NewInt(1 << 6)
	pageDeviceFieldImage      = big.NewInt(1 << 7)
	pageDeviceFieldIsWebcam   = big.NewInt(1 << 8)
	pageDeviceFieldAccount    = big.NewInt(1 << 9)
	pageDeviceFieldIsFavorite = big.NewInt(1 << 10)
	pageDeviceFieldUpdate     = big.NewInt(1 << 11)
	pageDeviceFieldData       = big.NewInt(1 << 12)
	pageDeviceFieldValues     = big.NewInt(1 << 13)
)

type PageDevice struct {
	Type *string `json:"type,omitempty" url:"type,omitempty"`
	// Device ID (numeric string)
	Code *string `json:"code,omitempty" url:"code,omitempty"`
	// Station name as set by the owner
	Name      *string `json:"name,omitempty" url:"name,omitempty"`
	City      *string `json:"city,omitempty" url:"city,omitempty"`
	Latitude  *string `json:"latitude,omitempty" url:"latitude,omitempty"`
	Longitude *string `json:"longitude,omitempty" url:"longitude,omitempty"`
	// Altitude in metres
	Elevation  *string `json:"elevation,omitempty" url:"elevation,omitempty"`
	Image      *string `json:"image,omitempty" url:"image,omitempty"`
	IsWebcam   *bool   `json:"isWebcam,omitempty" url:"isWebcam,omitempty"`
	Account    *int    `json:"account,omitempty" url:"account,omitempty"`
	IsFavorite *bool   `json:"isFavorite,omitempty" url:"isFavorite,omitempty"`
	// Seconds since last update
	Update *int `json:"update,omitempty" url:"update,omitempty"`
	// Distance from query point (km)
	Data *string `json:"data,omitempty" url:"data,omitempty"`
	// Scaled integer sensor readings — divide by 10 for most values.
	// e.g. `temp: 281` → 28.1°C, `bar: 10247` → 1024.7 hPa, `uvi: 70` → UV 7.0
	Values *PageDeviceValues `json:"values,omitempty" url:"values,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PageDevice) GetType() *string {
	if p == nil {
		return nil
	}
	return p.Type
}

func (p *PageDevice) GetCode() *string {
	if p == nil {
		return nil
	}
	return p.Code
}

func (p *PageDevice) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PageDevice) GetCity() *string {
	if p == nil {
		return nil
	}
	return p.City
}

func (p *PageDevice) GetLatitude() *string {
	if p == nil {
		return nil
	}
	return p.Latitude
}

func (p *PageDevice) GetLongitude() *string {
	if p == nil {
		return nil
	}
	return p.Longitude
}

func (p *PageDevice) GetElevation() *string {
	if p == nil {
		return nil
	}
	return p.Elevation
}

func (p *PageDevice) GetImage() *string {
	if p == nil {
		return nil
	}
	return p.Image
}

func (p *PageDevice) GetIsWebcam() *bool {
	if p == nil {
		return nil
	}
	return p.IsWebcam
}

func (p *PageDevice) GetAccount() *int {
	if p == nil {
		return nil
	}
	return p.Account
}

func (p *PageDevice) GetIsFavorite() *bool {
	if p == nil {
		return nil
	}
	return p.IsFavorite
}

func (p *PageDevice) GetUpdate() *int {
	if p == nil {
		return nil
	}
	return p.Update
}

func (p *PageDevice) GetData() *string {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PageDevice) GetValues() *PageDeviceValues {
	if p == nil {
		return nil
	}
	return p.Values
}

func (p *PageDevice) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PageDevice) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetType(type_ *string) {
	p.Type = type_
	p.require(pageDeviceFieldType)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetCode(code *string) {
	p.Code = code
	p.require(pageDeviceFieldCode)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetName(name *string) {
	p.Name = name
	p.require(pageDeviceFieldName)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetCity(city *string) {
	p.City = city
	p.require(pageDeviceFieldCity)
}

// SetLatitude sets the Latitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetLatitude(latitude *string) {
	p.Latitude = latitude
	p.require(pageDeviceFieldLatitude)
}

// SetLongitude sets the Longitude field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetLongitude(longitude *string) {
	p.Longitude = longitude
	p.require(pageDeviceFieldLongitude)
}

// SetElevation sets the Elevation field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetElevation(elevation *string) {
	p.Elevation = elevation
	p.require(pageDeviceFieldElevation)
}

// SetImage sets the Image field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetImage(image *string) {
	p.Image = image
	p.require(pageDeviceFieldImage)
}

// SetIsWebcam sets the IsWebcam field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetIsWebcam(isWebcam *bool) {
	p.IsWebcam = isWebcam
	p.require(pageDeviceFieldIsWebcam)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetAccount(account *int) {
	p.Account = account
	p.require(pageDeviceFieldAccount)
}

// SetIsFavorite sets the IsFavorite field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetIsFavorite(isFavorite *bool) {
	p.IsFavorite = isFavorite
	p.require(pageDeviceFieldIsFavorite)
}

// SetUpdate sets the Update field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetUpdate(update *int) {
	p.Update = update
	p.require(pageDeviceFieldUpdate)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetData(data *string) {
	p.Data = data
	p.require(pageDeviceFieldData)
}

// SetValues sets the Values field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevice) SetValues(values *PageDeviceValues) {
	p.Values = values
	p.require(pageDeviceFieldValues)
}

func (p *PageDevice) UnmarshalJSON(data []byte) error {
	type unmarshaler PageDevice
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PageDevice(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PageDevice) MarshalJSON() ([]byte, error) {
	type embed PageDevice
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PageDevice) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// Scaled integer sensor readings — divide by 10 for most values.
// e.g. `temp: 281` → 28.1°C, `bar: 10247` → 1024.7 hPa, `uvi: 70` → UV 7.0
var (
	pageDeviceValuesFieldEpoch    = big.NewInt(1 << 0)
	pageDeviceValuesFieldTemp     = big.NewInt(1 << 1)
	pageDeviceValuesFieldHum      = big.NewInt(1 << 2)
	pageDeviceValuesFieldDew      = big.NewInt(1 << 3)
	pageDeviceValuesFieldChill    = big.NewInt(1 << 4)
	pageDeviceValuesFieldHeat     = big.NewInt(1 << 5)
	pageDeviceValuesFieldBar      = big.NewInt(1 << 6)
	pageDeviceValuesFieldWdir     = big.NewInt(1 << 7)
	pageDeviceValuesFieldWspd     = big.NewInt(1 << 8)
	pageDeviceValuesFieldWspdavg  = big.NewInt(1 << 9)
	pageDeviceValuesFieldWspdhi   = big.NewInt(1 << 10)
	pageDeviceValuesFieldRainrate = big.NewInt(1 << 11)
	pageDeviceValuesFieldRain     = big.NewInt(1 << 12)
	pageDeviceValuesFieldSolarrad = big.NewInt(1 << 13)
	pageDeviceValuesFieldUvi      = big.NewInt(1 << 14)
	pageDeviceValuesFieldTempin   = big.NewInt(1 << 15)
	pageDeviceValuesFieldHumin    = big.NewInt(1 << 16)
)

type PageDeviceValues struct {
	Epoch    *string `json:"epoch,omitempty" url:"epoch,omitempty"`
	Temp     *string `json:"temp,omitempty" url:"temp,omitempty"`
	Hum      *string `json:"hum,omitempty" url:"hum,omitempty"`
	Dew      *string `json:"dew,omitempty" url:"dew,omitempty"`
	Chill    *string `json:"chill,omitempty" url:"chill,omitempty"`
	Heat     *string `json:"heat,omitempty" url:"heat,omitempty"`
	Bar      *string `json:"bar,omitempty" url:"bar,omitempty"`
	Wdir     *string `json:"wdir,omitempty" url:"wdir,omitempty"`
	Wspd     *string `json:"wspd,omitempty" url:"wspd,omitempty"`
	Wspdavg  *string `json:"wspdavg,omitempty" url:"wspdavg,omitempty"`
	Wspdhi   *string `json:"wspdhi,omitempty" url:"wspdhi,omitempty"`
	Rainrate *string `json:"rainrate,omitempty" url:"rainrate,omitempty"`
	Rain     *string `json:"rain,omitempty" url:"rain,omitempty"`
	Solarrad *string `json:"solarrad,omitempty" url:"solarrad,omitempty"`
	Uvi      *string `json:"uvi,omitempty" url:"uvi,omitempty"`
	// Indoor temperature (°C, scaled ×10) — if sensor present
	Tempin *string `json:"tempin,omitempty" url:"tempin,omitempty"`
	// Indoor humidity (%, scaled ×10) — if sensor present
	Humin *string `json:"humin,omitempty" url:"humin,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PageDeviceValues) GetEpoch() *string {
	if p == nil {
		return nil
	}
	return p.Epoch
}

func (p *PageDeviceValues) GetTemp() *string {
	if p == nil {
		return nil
	}
	return p.Temp
}

func (p *PageDeviceValues) GetHum() *string {
	if p == nil {
		return nil
	}
	return p.Hum
}

func (p *PageDeviceValues) GetDew() *string {
	if p == nil {
		return nil
	}
	return p.Dew
}

func (p *PageDeviceValues) GetChill() *string {
	if p == nil {
		return nil
	}
	return p.Chill
}

func (p *PageDeviceValues) GetHeat() *string {
	if p == nil {
		return nil
	}
	return p.Heat
}

func (p *PageDeviceValues) GetBar() *string {
	if p == nil {
		return nil
	}
	return p.Bar
}

func (p *PageDeviceValues) GetWdir() *string {
	if p == nil {
		return nil
	}
	return p.Wdir
}

func (p *PageDeviceValues) GetWspd() *string {
	if p == nil {
		return nil
	}
	return p.Wspd
}

func (p *PageDeviceValues) GetWspdavg() *string {
	if p == nil {
		return nil
	}
	return p.Wspdavg
}

func (p *PageDeviceValues) GetWspdhi() *string {
	if p == nil {
		return nil
	}
	return p.Wspdhi
}

func (p *PageDeviceValues) GetRainrate() *string {
	if p == nil {
		return nil
	}
	return p.Rainrate
}

func (p *PageDeviceValues) GetRain() *string {
	if p == nil {
		return nil
	}
	return p.Rain
}

func (p *PageDeviceValues) GetSolarrad() *string {
	if p == nil {
		return nil
	}
	return p.Solarrad
}

func (p *PageDeviceValues) GetUvi() *string {
	if p == nil {
		return nil
	}
	return p.Uvi
}

func (p *PageDeviceValues) GetTempin() *string {
	if p == nil {
		return nil
	}
	return p.Tempin
}

func (p *PageDeviceValues) GetHumin() *string {
	if p == nil {
		return nil
	}
	return p.Humin
}

func (p *PageDeviceValues) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PageDeviceValues) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetEpoch sets the Epoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetEpoch(epoch *string) {
	p.Epoch = epoch
	p.require(pageDeviceValuesFieldEpoch)
}

// SetTemp sets the Temp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetTemp(temp *string) {
	p.Temp = temp
	p.require(pageDeviceValuesFieldTemp)
}

// SetHum sets the Hum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetHum(hum *string) {
	p.Hum = hum
	p.require(pageDeviceValuesFieldHum)
}

// SetDew sets the Dew field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetDew(dew *string) {
	p.Dew = dew
	p.require(pageDeviceValuesFieldDew)
}

// SetChill sets the Chill field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetChill(chill *string) {
	p.Chill = chill
	p.require(pageDeviceValuesFieldChill)
}

// SetHeat sets the Heat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetHeat(heat *string) {
	p.Heat = heat
	p.require(pageDeviceValuesFieldHeat)
}

// SetBar sets the Bar field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetBar(bar *string) {
	p.Bar = bar
	p.require(pageDeviceValuesFieldBar)
}

// SetWdir sets the Wdir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetWdir(wdir *string) {
	p.Wdir = wdir
	p.require(pageDeviceValuesFieldWdir)
}

// SetWspd sets the Wspd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetWspd(wspd *string) {
	p.Wspd = wspd
	p.require(pageDeviceValuesFieldWspd)
}

// SetWspdavg sets the Wspdavg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetWspdavg(wspdavg *string) {
	p.Wspdavg = wspdavg
	p.require(pageDeviceValuesFieldWspdavg)
}

// SetWspdhi sets the Wspdhi field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetWspdhi(wspdhi *string) {
	p.Wspdhi = wspdhi
	p.require(pageDeviceValuesFieldWspdhi)
}

// SetRainrate sets the Rainrate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetRainrate(rainrate *string) {
	p.Rainrate = rainrate
	p.require(pageDeviceValuesFieldRainrate)
}

// SetRain sets the Rain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetRain(rain *string) {
	p.Rain = rain
	p.require(pageDeviceValuesFieldRain)
}

// SetSolarrad sets the Solarrad field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetSolarrad(solarrad *string) {
	p.Solarrad = solarrad
	p.require(pageDeviceValuesFieldSolarrad)
}

// SetUvi sets the Uvi field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetUvi(uvi *string) {
	p.Uvi = uvi
	p.require(pageDeviceValuesFieldUvi)
}

// SetTempin sets the Tempin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetTempin(tempin *string) {
	p.Tempin = tempin
	p.require(pageDeviceValuesFieldTempin)
}

// SetHumin sets the Humin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDeviceValues) SetHumin(humin *string) {
	p.Humin = humin
	p.require(pageDeviceValuesFieldHumin)
}

func (p *PageDeviceValues) UnmarshalJSON(data []byte) error {
	type unmarshaler PageDeviceValues
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PageDeviceValues(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PageDeviceValues) MarshalJSON() ([]byte, error) {
	type embed PageDeviceValues
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PageDeviceValues) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	pageDevicesResponseFieldDevices = big.NewInt(1 << 0)
)

type PageDevicesResponse struct {
	Devices []*PageDevice `json:"devices,omitempty" url:"devices,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PageDevicesResponse) GetDevices() []*PageDevice {
	if p == nil {
		return nil
	}
	return p.Devices
}

func (p *PageDevicesResponse) GetExtraProperties() map[string]interface{} {
	if p == nil {
		return nil
	}
	return p.extraProperties
}

func (p *PageDevicesResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetDevices sets the Devices field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PageDevicesResponse) SetDevices(devices []*PageDevice) {
	p.Devices = devices
	p.require(pageDevicesResponseFieldDevices)
}

func (p *PageDevicesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PageDevicesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PageDevicesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PageDevicesResponse) MarshalJSON() ([]byte, error) {
	type embed PageDevicesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PageDevicesResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type GetPopularStationsRequestPeriod string

const (
	GetPopularStationsRequestPeriodDay   GetPopularStationsRequestPeriod = "day"
	GetPopularStationsRequestPeriodWeek  GetPopularStationsRequestPeriod = "week"
	GetPopularStationsRequestPeriodMonth GetPopularStationsRequestPeriod = "month"
)

func NewGetPopularStationsRequestPeriodFromString(s string) (GetPopularStationsRequestPeriod, error) {
	switch s {
	case "day":
		return GetPopularStationsRequestPeriodDay, nil
	case "week":
		return GetPopularStationsRequestPeriodWeek, nil
	case "month":
		return GetPopularStationsRequestPeriodMonth, nil
	}
	var t GetPopularStationsRequestPeriod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (g GetPopularStationsRequestPeriod) Ptr() *GetPopularStationsRequestPeriod {
	return &g
}
