// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGetMostFollowedStationsRequest(t *testing.T) {
	t.Run("SetCountry", func(t *testing.T) {
		obj := &GetMostFollowedStationsRequest{}
		var fernTestValueCountry string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetMostFollowedStationsRequest(t *testing.T) {
	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetMostFollowedStationsRequest{}
		var fernTestValueCountry string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetNearbyStationsRequest(t *testing.T) {
	t.Run("SetLat", func(t *testing.T) {
		obj := &GetNearbyStationsRequest{}
		var fernTestValueLat float64
		obj.SetLat(fernTestValueLat)
		assert.Equal(t, fernTestValueLat, obj.Lat)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLon", func(t *testing.T) {
		obj := &GetNearbyStationsRequest{}
		var fernTestValueLon float64
		obj.SetLon(fernTestValueLon)
		assert.Equal(t, fernTestValueLon, obj.Lon)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKm", func(t *testing.T) {
		obj := &GetNearbyStationsRequest{}
		var fernTestValueKm int
		obj.SetKm(fernTestValueKm)
		assert.Equal(t, fernTestValueKm, obj.Km)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetNearbyStationsRequest(t *testing.T) {
	t.Run("SetLat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNearbyStationsRequest{}
		var fernTestValueLat float64

		// Act
		obj.SetLat(fernTestValueLat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLon_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNearbyStationsRequest{}
		var fernTestValueLon float64

		// Act
		obj.SetLon(fernTestValueLon)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKm_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNearbyStationsRequest{}
		var fernTestValueKm int

		// Act
		obj.SetKm(fernTestValueKm)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetNewestStationsRequest(t *testing.T) {
	t.Run("SetCountry", func(t *testing.T) {
		obj := &GetNewestStationsRequest{}
		var fernTestValueCountry string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetNewestStationsRequest(t *testing.T) {
	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetNewestStationsRequest{}
		var fernTestValueCountry string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetPopularStationsRequest(t *testing.T) {
	t.Run("SetCountry", func(t *testing.T) {
		obj := &GetPopularStationsRequest{}
		var fernTestValueCountry string
		obj.SetCountry(fernTestValueCountry)
		assert.Equal(t, fernTestValueCountry, obj.Country)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPeriod", func(t *testing.T) {
		obj := &GetPopularStationsRequest{}
		var fernTestValuePeriod GetPopularStationsRequestPeriod
		obj.SetPeriod(fernTestValuePeriod)
		assert.Equal(t, fernTestValuePeriod, obj.Period)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetPopularStationsRequest(t *testing.T) {
	t.Run("SetCountry_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPopularStationsRequest{}
		var fernTestValueCountry string

		// Act
		obj.SetCountry(fernTestValueCountry)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPeriod_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetPopularStationsRequest{}
		var fernTestValuePeriod GetPopularStationsRequestPeriod

		// Act
		obj.SetPeriod(fernTestValuePeriod)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetStationPageStationsRequest(t *testing.T) {
	t.Run("SetDeviceID", func(t *testing.T) {
		obj := &GetStationPageStationsRequest{}
		var fernTestValueDeviceID string
		obj.SetDeviceID(fernTestValueDeviceID)
		assert.Equal(t, fernTestValueDeviceID, obj.DeviceID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetStationPageStationsRequest(t *testing.T) {
	t.Run("SetDeviceID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetStationPageStationsRequest{}
		var fernTestValueDeviceID string

		// Act
		obj.SetDeviceID(fernTestValueDeviceID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPageDevice(t *testing.T) {
	t.Run("SetType", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueType *string
		obj.SetType(fernTestValueType)
		assert.Equal(t, fernTestValueType, obj.Type)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCode", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueCode *string
		obj.SetCode(fernTestValueCode)
		assert.Equal(t, fernTestValueCode, obj.Code)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetName", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCity", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueCity *string
		obj.SetCity(fernTestValueCity)
		assert.Equal(t, fernTestValueCity, obj.City)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLatitude", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueLatitude *string
		obj.SetLatitude(fernTestValueLatitude)
		assert.Equal(t, fernTestValueLatitude, obj.Latitude)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLongitude", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueLongitude *string
		obj.SetLongitude(fernTestValueLongitude)
		assert.Equal(t, fernTestValueLongitude, obj.Longitude)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetElevation", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueElevation *string
		obj.SetElevation(fernTestValueElevation)
		assert.Equal(t, fernTestValueElevation, obj.Elevation)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetImage", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueImage *string
		obj.SetImage(fernTestValueImage)
		assert.Equal(t, fernTestValueImage, obj.Image)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsWebcam", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueIsWebcam *bool
		obj.SetIsWebcam(fernTestValueIsWebcam)
		assert.Equal(t, fernTestValueIsWebcam, obj.IsWebcam)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccount", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueAccount *int
		obj.SetAccount(fernTestValueAccount)
		assert.Equal(t, fernTestValueAccount, obj.Account)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetIsFavorite", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueIsFavorite *bool
		obj.SetIsFavorite(fernTestValueIsFavorite)
		assert.Equal(t, fernTestValueIsFavorite, obj.IsFavorite)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUpdate", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueUpdate *int
		obj.SetUpdate(fernTestValueUpdate)
		assert.Equal(t, fernTestValueUpdate, obj.Update)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetData", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueData *string
		obj.SetData(fernTestValueData)
		assert.Equal(t, fernTestValueData, obj.Data)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetValues", func(t *testing.T) {
		obj := &PageDevice{}
		var fernTestValueValues *PageDeviceValues
		obj.SetValues(fernTestValueValues)
		assert.Equal(t, fernTestValueValues, obj.Values)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPageDevice(t *testing.T) {
	t.Run("GetType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Type = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetType(), "getter should return the property value")
	})

	t.Run("GetType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Type = nil

		// Act & Assert
		assert.Nil(t, obj.GetType(), "getter should return nil when property is nil")
	})

	t.Run("GetType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetType() // Should return zero value
	})

	t.Run("GetCode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Code = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCode(), "getter should return the property value")
	})

	t.Run("GetCode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Code = nil

		// Act & Assert
		assert.Nil(t, obj.GetCode(), "getter should return nil when property is nil")
	})

	t.Run("GetCode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCode() // Should return zero value
	})

	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetCity", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.City = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetCity(), "getter should return the property value")
	})

	t.Run("GetCity_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.City = nil

		// Act & Assert
		assert.Nil(t, obj.GetCity(), "getter should return nil when property is nil")
	})

	t.Run("GetCity_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetCity() // Should return zero value
	})

	t.Run("GetLatitude", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Latitude = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLatitude(), "getter should return the property value")
	})

	t.Run("GetLatitude_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Latitude = nil

		// Act & Assert
		assert.Nil(t, obj.GetLatitude(), "getter should return nil when property is nil")
	})

	t.Run("GetLatitude_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLatitude() // Should return zero value
	})

	t.Run("GetLongitude", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Longitude = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLongitude(), "getter should return the property value")
	})

	t.Run("GetLongitude_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Longitude = nil

		// Act & Assert
		assert.Nil(t, obj.GetLongitude(), "getter should return nil when property is nil")
	})

	t.Run("GetLongitude_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLongitude() // Should return zero value
	})

	t.Run("GetElevation", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Elevation = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetElevation(), "getter should return the property value")
	})

	t.Run("GetElevation_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Elevation = nil

		// Act & Assert
		assert.Nil(t, obj.GetElevation(), "getter should return nil when property is nil")
	})

	t.Run("GetElevation_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetElevation() // Should return zero value
	})

	t.Run("GetImage", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Image = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetImage(), "getter should return the property value")
	})

	t.Run("GetImage_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Image = nil

		// Act & Assert
		assert.Nil(t, obj.GetImage(), "getter should return nil when property is nil")
	})

	t.Run("GetImage_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetImage() // Should return zero value
	})

	t.Run("GetIsWebcam", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *bool
		obj.IsWebcam = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsWebcam(), "getter should return the property value")
	})

	t.Run("GetIsWebcam_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.IsWebcam = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsWebcam(), "getter should return nil when property is nil")
	})

	t.Run("GetIsWebcam_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsWebcam() // Should return zero value
	})

	t.Run("GetAccount", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *int
		obj.Account = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetAccount(), "getter should return the property value")
	})

	t.Run("GetAccount_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Account = nil

		// Act & Assert
		assert.Nil(t, obj.GetAccount(), "getter should return nil when property is nil")
	})

	t.Run("GetAccount_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetAccount() // Should return zero value
	})

	t.Run("GetIsFavorite", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *bool
		obj.IsFavorite = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetIsFavorite(), "getter should return the property value")
	})

	t.Run("GetIsFavorite_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.IsFavorite = nil

		// Act & Assert
		assert.Nil(t, obj.GetIsFavorite(), "getter should return nil when property is nil")
	})

	t.Run("GetIsFavorite_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetIsFavorite() // Should return zero value
	})

	t.Run("GetUpdate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *int
		obj.Update = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUpdate(), "getter should return the property value")
	})

	t.Run("GetUpdate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Update = nil

		// Act & Assert
		assert.Nil(t, obj.GetUpdate(), "getter should return nil when property is nil")
	})

	t.Run("GetUpdate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUpdate() // Should return zero value
	})

	t.Run("GetData", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *string
		obj.Data = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetData(), "getter should return the property value")
	})

	t.Run("GetData_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Data = nil

		// Act & Assert
		assert.Nil(t, obj.GetData(), "getter should return nil when property is nil")
	})

	t.Run("GetData_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetData() // Should return zero value
	})

	t.Run("GetValues", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var expected *PageDeviceValues
		obj.Values = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetValues(), "getter should return the property value")
	})

	t.Run("GetValues_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		obj.Values = nil

		// Act & Assert
		assert.Nil(t, obj.GetValues(), "getter should return nil when property is nil")
	})

	t.Run("GetValues_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetValues() // Should return zero value
	})

}

func TestSettersMarkExplicitPageDevice(t *testing.T) {
	t.Run("SetType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueType *string

		// Act
		obj.SetType(fernTestValueType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueCode *string

		// Act
		obj.SetCode(fernTestValueCode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCity_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueCity *string

		// Act
		obj.SetCity(fernTestValueCity)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLatitude_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueLatitude *string

		// Act
		obj.SetLatitude(fernTestValueLatitude)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLongitude_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueLongitude *string

		// Act
		obj.SetLongitude(fernTestValueLongitude)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetElevation_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueElevation *string

		// Act
		obj.SetElevation(fernTestValueElevation)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetImage_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueImage *string

		// Act
		obj.SetImage(fernTestValueImage)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsWebcam_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueIsWebcam *bool

		// Act
		obj.SetIsWebcam(fernTestValueIsWebcam)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccount_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueAccount *int

		// Act
		obj.SetAccount(fernTestValueAccount)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetIsFavorite_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueIsFavorite *bool

		// Act
		obj.SetIsFavorite(fernTestValueIsFavorite)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUpdate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueUpdate *int

		// Act
		obj.SetUpdate(fernTestValueUpdate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetData_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueData *string

		// Act
		obj.SetData(fernTestValueData)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetValues_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}
		var fernTestValueValues *PageDeviceValues

		// Act
		obj.SetValues(fernTestValueValues)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPageDeviceValues(t *testing.T) {
	t.Run("SetEpoch", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueEpoch *string
		obj.SetEpoch(fernTestValueEpoch)
		assert.Equal(t, fernTestValueEpoch, obj.Epoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTemp", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueTemp *string
		obj.SetTemp(fernTestValueTemp)
		assert.Equal(t, fernTestValueTemp, obj.Temp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHum", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueHum *string
		obj.SetHum(fernTestValueHum)
		assert.Equal(t, fernTestValueHum, obj.Hum)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDew", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueDew *string
		obj.SetDew(fernTestValueDew)
		assert.Equal(t, fernTestValueDew, obj.Dew)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChill", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueChill *string
		obj.SetChill(fernTestValueChill)
		assert.Equal(t, fernTestValueChill, obj.Chill)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeat", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueHeat *string
		obj.SetHeat(fernTestValueHeat)
		assert.Equal(t, fernTestValueHeat, obj.Heat)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBar", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueBar *string
		obj.SetBar(fernTestValueBar)
		assert.Equal(t, fernTestValueBar, obj.Bar)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWdir", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueWdir *string
		obj.SetWdir(fernTestValueWdir)
		assert.Equal(t, fernTestValueWdir, obj.Wdir)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspd", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueWspd *string
		obj.SetWspd(fernTestValueWspd)
		assert.Equal(t, fernTestValueWspd, obj.Wspd)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspdavg", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueWspdavg *string
		obj.SetWspdavg(fernTestValueWspdavg)
		assert.Equal(t, fernTestValueWspdavg, obj.Wspdavg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspdhi", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueWspdhi *string
		obj.SetWspdhi(fernTestValueWspdhi)
		assert.Equal(t, fernTestValueWspdhi, obj.Wspdhi)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRainrate", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueRainrate *string
		obj.SetRainrate(fernTestValueRainrate)
		assert.Equal(t, fernTestValueRainrate, obj.Rainrate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRain", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueRain *string
		obj.SetRain(fernTestValueRain)
		assert.Equal(t, fernTestValueRain, obj.Rain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSolarrad", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueSolarrad *string
		obj.SetSolarrad(fernTestValueSolarrad)
		assert.Equal(t, fernTestValueSolarrad, obj.Solarrad)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUvi", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueUvi *string
		obj.SetUvi(fernTestValueUvi)
		assert.Equal(t, fernTestValueUvi, obj.Uvi)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTempin", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueTempin *string
		obj.SetTempin(fernTestValueTempin)
		assert.Equal(t, fernTestValueTempin, obj.Tempin)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHumin", func(t *testing.T) {
		obj := &PageDeviceValues{}
		var fernTestValueHumin *string
		obj.SetHumin(fernTestValueHumin)
		assert.Equal(t, fernTestValueHumin, obj.Humin)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPageDeviceValues(t *testing.T) {
	t.Run("GetEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Epoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEpoch(), "getter should return the property value")
	})

	t.Run("GetEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Epoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEpoch() // Should return zero value
	})

	t.Run("GetTemp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Temp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTemp(), "getter should return the property value")
	})

	t.Run("GetTemp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Temp = nil

		// Act & Assert
		assert.Nil(t, obj.GetTemp(), "getter should return nil when property is nil")
	})

	t.Run("GetTemp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTemp() // Should return zero value
	})

	t.Run("GetHum", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Hum = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHum(), "getter should return the property value")
	})

	t.Run("GetHum_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Hum = nil

		// Act & Assert
		assert.Nil(t, obj.GetHum(), "getter should return nil when property is nil")
	})

	t.Run("GetHum_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHum() // Should return zero value
	})

	t.Run("GetDew", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Dew = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDew(), "getter should return the property value")
	})

	t.Run("GetDew_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Dew = nil

		// Act & Assert
		assert.Nil(t, obj.GetDew(), "getter should return nil when property is nil")
	})

	t.Run("GetDew_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDew() // Should return zero value
	})

	t.Run("GetChill", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Chill = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetChill(), "getter should return the property value")
	})

	t.Run("GetChill_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Chill = nil

		// Act & Assert
		assert.Nil(t, obj.GetChill(), "getter should return nil when property is nil")
	})

	t.Run("GetChill_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetChill() // Should return zero value
	})

	t.Run("GetHeat", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Heat = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeat(), "getter should return the property value")
	})

	t.Run("GetHeat_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Heat = nil

		// Act & Assert
		assert.Nil(t, obj.GetHeat(), "getter should return nil when property is nil")
	})

	t.Run("GetHeat_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeat() // Should return zero value
	})

	t.Run("GetBar", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Bar = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBar(), "getter should return the property value")
	})

	t.Run("GetBar_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Bar = nil

		// Act & Assert
		assert.Nil(t, obj.GetBar(), "getter should return nil when property is nil")
	})

	t.Run("GetBar_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBar() // Should return zero value
	})

	t.Run("GetWdir", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Wdir = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWdir(), "getter should return the property value")
	})

	t.Run("GetWdir_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Wdir = nil

		// Act & Assert
		assert.Nil(t, obj.GetWdir(), "getter should return nil when property is nil")
	})

	t.Run("GetWdir_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWdir() // Should return zero value
	})

	t.Run("GetWspd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Wspd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspd(), "getter should return the property value")
	})

	t.Run("GetWspd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Wspd = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspd(), "getter should return nil when property is nil")
	})

	t.Run("GetWspd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspd() // Should return zero value
	})

	t.Run("GetWspdavg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Wspdavg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspdavg(), "getter should return the property value")
	})

	t.Run("GetWspdavg_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Wspdavg = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspdavg(), "getter should return nil when property is nil")
	})

	t.Run("GetWspdavg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspdavg() // Should return zero value
	})

	t.Run("GetWspdhi", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Wspdhi = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspdhi(), "getter should return the property value")
	})

	t.Run("GetWspdhi_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Wspdhi = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspdhi(), "getter should return nil when property is nil")
	})

	t.Run("GetWspdhi_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspdhi() // Should return zero value
	})

	t.Run("GetRainrate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Rainrate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRainrate(), "getter should return the property value")
	})

	t.Run("GetRainrate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Rainrate = nil

		// Act & Assert
		assert.Nil(t, obj.GetRainrate(), "getter should return nil when property is nil")
	})

	t.Run("GetRainrate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRainrate() // Should return zero value
	})

	t.Run("GetRain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Rain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRain(), "getter should return the property value")
	})

	t.Run("GetRain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Rain = nil

		// Act & Assert
		assert.Nil(t, obj.GetRain(), "getter should return nil when property is nil")
	})

	t.Run("GetRain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRain() // Should return zero value
	})

	t.Run("GetSolarrad", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Solarrad = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSolarrad(), "getter should return the property value")
	})

	t.Run("GetSolarrad_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Solarrad = nil

		// Act & Assert
		assert.Nil(t, obj.GetSolarrad(), "getter should return nil when property is nil")
	})

	t.Run("GetSolarrad_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSolarrad() // Should return zero value
	})

	t.Run("GetUvi", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Uvi = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUvi(), "getter should return the property value")
	})

	t.Run("GetUvi_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Uvi = nil

		// Act & Assert
		assert.Nil(t, obj.GetUvi(), "getter should return nil when property is nil")
	})

	t.Run("GetUvi_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUvi() // Should return zero value
	})

	t.Run("GetTempin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Tempin = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTempin(), "getter should return the property value")
	})

	t.Run("GetTempin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Tempin = nil

		// Act & Assert
		assert.Nil(t, obj.GetTempin(), "getter should return nil when property is nil")
	})

	t.Run("GetTempin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTempin() // Should return zero value
	})

	t.Run("GetHumin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var expected *string
		obj.Humin = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHumin(), "getter should return the property value")
	})

	t.Run("GetHumin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		obj.Humin = nil

		// Act & Assert
		assert.Nil(t, obj.GetHumin(), "getter should return nil when property is nil")
	})

	t.Run("GetHumin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHumin() // Should return zero value
	})

}

func TestSettersMarkExplicitPageDeviceValues(t *testing.T) {
	t.Run("SetEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueEpoch *string

		// Act
		obj.SetEpoch(fernTestValueEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTemp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueTemp *string

		// Act
		obj.SetTemp(fernTestValueTemp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHum_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueHum *string

		// Act
		obj.SetHum(fernTestValueHum)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDew_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueDew *string

		// Act
		obj.SetDew(fernTestValueDew)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChill_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueChill *string

		// Act
		obj.SetChill(fernTestValueChill)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueHeat *string

		// Act
		obj.SetHeat(fernTestValueHeat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBar_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueBar *string

		// Act
		obj.SetBar(fernTestValueBar)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWdir_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueWdir *string

		// Act
		obj.SetWdir(fernTestValueWdir)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueWspd *string

		// Act
		obj.SetWspd(fernTestValueWspd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspdavg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueWspdavg *string

		// Act
		obj.SetWspdavg(fernTestValueWspdavg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspdhi_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueWspdhi *string

		// Act
		obj.SetWspdhi(fernTestValueWspdhi)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRainrate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueRainrate *string

		// Act
		obj.SetRainrate(fernTestValueRainrate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueRain *string

		// Act
		obj.SetRain(fernTestValueRain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSolarrad_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueSolarrad *string

		// Act
		obj.SetSolarrad(fernTestValueSolarrad)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUvi_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueUvi *string

		// Act
		obj.SetUvi(fernTestValueUvi)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTempin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueTempin *string

		// Act
		obj.SetTempin(fernTestValueTempin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHumin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}
		var fernTestValueHumin *string

		// Act
		obj.SetHumin(fernTestValueHumin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersPageDevicesResponse(t *testing.T) {
	t.Run("SetDevices", func(t *testing.T) {
		obj := &PageDevicesResponse{}
		var fernTestValueDevices []*PageDevice
		obj.SetDevices(fernTestValueDevices)
		assert.Equal(t, fernTestValueDevices, obj.Devices)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersPageDevicesResponse(t *testing.T) {
	t.Run("GetDevices", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevicesResponse{}
		var expected []*PageDevice
		obj.Devices = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDevices(), "getter should return the property value")
	})

	t.Run("GetDevices_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevicesResponse{}
		obj.Devices = nil

		// Act & Assert
		assert.Nil(t, obj.GetDevices(), "getter should return nil when property is nil")
	})

	t.Run("GetDevices_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevicesResponse
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDevices() // Should return zero value
	})

}

func TestSettersMarkExplicitPageDevicesResponse(t *testing.T) {
	t.Run("SetDevices_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevicesResponse{}
		var fernTestValueDevices []*PageDevice

		// Act
		obj.SetDevices(fernTestValueDevices)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingPageDevice(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevice{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PageDevice
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PageDevice
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PageDevice
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPageDeviceValues(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDeviceValues{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PageDeviceValues
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PageDeviceValues
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PageDeviceValues
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingPageDevicesResponse(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &PageDevicesResponse{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled PageDevicesResponse
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj PageDevicesResponse
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj PageDevicesResponse
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringPageDevice(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PageDevice{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPageDeviceValues(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PageDeviceValues{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringPageDevicesResponse(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &PageDevicesResponse{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevicesResponse
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumGetPopularStationsRequestPeriod(t *testing.T) {
	t.Run("NewFromString_day", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetPopularStationsRequestPeriodFromString("day")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetPopularStationsRequestPeriod("day"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_week", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetPopularStationsRequestPeriodFromString("week")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetPopularStationsRequestPeriod("week"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_month", func(t *testing.T) {
		t.Parallel()
		val, err := NewGetPopularStationsRequestPeriodFromString("month")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, GetPopularStationsRequestPeriod("month"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewGetPopularStationsRequestPeriodFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewGetPopularStationsRequestPeriodFromString("day")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesPageDevice(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PageDevice{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevice
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPageDeviceValues(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PageDeviceValues{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDeviceValues
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesPageDevicesResponse(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &PageDevicesResponse{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *PageDevicesResponse
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
