// Code generated by Fern. DO NOT EDIT.

package weathercloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersDeviceValues(t *testing.T) {
	t.Run("SetEpoch", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueEpoch *int
		obj.SetEpoch(fernTestValueEpoch)
		assert.Equal(t, fernTestValueEpoch, obj.Epoch)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTemp", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueTemp *float64
		obj.SetTemp(fernTestValueTemp)
		assert.Equal(t, fernTestValueTemp, obj.Temp)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDew", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueDew *float64
		obj.SetDew(fernTestValueDew)
		assert.Equal(t, fernTestValueDew, obj.Dew)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetChill", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueChill *float64
		obj.SetChill(fernTestValueChill)
		assert.Equal(t, fernTestValueChill, obj.Chill)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeat", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueHeat *float64
		obj.SetHeat(fernTestValueHeat)
		assert.Equal(t, fernTestValueHeat, obj.Heat)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHum", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueHum *int
		obj.SetHum(fernTestValueHum)
		assert.Equal(t, fernTestValueHum, obj.Hum)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBar", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueBar *float64
		obj.SetBar(fernTestValueBar)
		assert.Equal(t, fernTestValueBar, obj.Bar)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWdir", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueWdir *int
		obj.SetWdir(fernTestValueWdir)
		assert.Equal(t, fernTestValueWdir, obj.Wdir)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWdiravg", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueWdiravg *int
		obj.SetWdiravg(fernTestValueWdiravg)
		assert.Equal(t, fernTestValueWdiravg, obj.Wdiravg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspd", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueWspd *float64
		obj.SetWspd(fernTestValueWspd)
		assert.Equal(t, fernTestValueWspd, obj.Wspd)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspdavg", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueWspdavg *float64
		obj.SetWspdavg(fernTestValueWspdavg)
		assert.Equal(t, fernTestValueWspdavg, obj.Wspdavg)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWspdhi", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueWspdhi *float64
		obj.SetWspdhi(fernTestValueWspdhi)
		assert.Equal(t, fernTestValueWspdhi, obj.Wspdhi)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRainrate", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueRainrate *float64
		obj.SetRainrate(fernTestValueRainrate)
		assert.Equal(t, fernTestValueRainrate, obj.Rainrate)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRain", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueRain *float64
		obj.SetRain(fernTestValueRain)
		assert.Equal(t, fernTestValueRain, obj.Rain)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSolarrad", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueSolarrad *float64
		obj.SetSolarrad(fernTestValueSolarrad)
		assert.Equal(t, fernTestValueSolarrad, obj.Solarrad)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetUvi", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueUvi *float64
		obj.SetUvi(fernTestValueUvi)
		assert.Equal(t, fernTestValueUvi, obj.Uvi)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetTempin", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueTempin *float64
		obj.SetTempin(fernTestValueTempin)
		assert.Equal(t, fernTestValueTempin, obj.Tempin)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHumin", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueHumin *int
		obj.SetHumin(fernTestValueHumin)
		assert.Equal(t, fernTestValueHumin, obj.Humin)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetHeatin", func(t *testing.T) {
		obj := &DeviceValues{}
		var fernTestValueHeatin *float64
		obj.SetHeatin(fernTestValueHeatin)
		assert.Equal(t, fernTestValueHeatin, obj.Heatin)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersDeviceValues(t *testing.T) {
	t.Run("GetEpoch", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *int
		obj.Epoch = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetEpoch(), "getter should return the property value")
	})

	t.Run("GetEpoch_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Epoch = nil

		// Act & Assert
		assert.Nil(t, obj.GetEpoch(), "getter should return nil when property is nil")
	})

	t.Run("GetEpoch_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetEpoch() // Should return zero value
	})

	t.Run("GetTemp", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Temp = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTemp(), "getter should return the property value")
	})

	t.Run("GetTemp_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Temp = nil

		// Act & Assert
		assert.Nil(t, obj.GetTemp(), "getter should return nil when property is nil")
	})

	t.Run("GetTemp_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTemp() // Should return zero value
	})

	t.Run("GetDew", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Dew = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDew(), "getter should return the property value")
	})

	t.Run("GetDew_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Dew = nil

		// Act & Assert
		assert.Nil(t, obj.GetDew(), "getter should return nil when property is nil")
	})

	t.Run("GetDew_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDew() // Should return zero value
	})

	t.Run("GetChill", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Chill = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetChill(), "getter should return the property value")
	})

	t.Run("GetChill_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Chill = nil

		// Act & Assert
		assert.Nil(t, obj.GetChill(), "getter should return nil when property is nil")
	})

	t.Run("GetChill_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetChill() // Should return zero value
	})

	t.Run("GetHeat", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Heat = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeat(), "getter should return the property value")
	})

	t.Run("GetHeat_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Heat = nil

		// Act & Assert
		assert.Nil(t, obj.GetHeat(), "getter should return nil when property is nil")
	})

	t.Run("GetHeat_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeat() // Should return zero value
	})

	t.Run("GetHum", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *int
		obj.Hum = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHum(), "getter should return the property value")
	})

	t.Run("GetHum_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Hum = nil

		// Act & Assert
		assert.Nil(t, obj.GetHum(), "getter should return nil when property is nil")
	})

	t.Run("GetHum_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHum() // Should return zero value
	})

	t.Run("GetBar", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Bar = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBar(), "getter should return the property value")
	})

	t.Run("GetBar_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Bar = nil

		// Act & Assert
		assert.Nil(t, obj.GetBar(), "getter should return nil when property is nil")
	})

	t.Run("GetBar_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBar() // Should return zero value
	})

	t.Run("GetWdir", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *int
		obj.Wdir = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWdir(), "getter should return the property value")
	})

	t.Run("GetWdir_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Wdir = nil

		// Act & Assert
		assert.Nil(t, obj.GetWdir(), "getter should return nil when property is nil")
	})

	t.Run("GetWdir_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWdir() // Should return zero value
	})

	t.Run("GetWdiravg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *int
		obj.Wdiravg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWdiravg(), "getter should return the property value")
	})

	t.Run("GetWdiravg_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Wdiravg = nil

		// Act & Assert
		assert.Nil(t, obj.GetWdiravg(), "getter should return nil when property is nil")
	})

	t.Run("GetWdiravg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWdiravg() // Should return zero value
	})

	t.Run("GetWspd", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Wspd = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspd(), "getter should return the property value")
	})

	t.Run("GetWspd_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Wspd = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspd(), "getter should return nil when property is nil")
	})

	t.Run("GetWspd_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspd() // Should return zero value
	})

	t.Run("GetWspdavg", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Wspdavg = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspdavg(), "getter should return the property value")
	})

	t.Run("GetWspdavg_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Wspdavg = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspdavg(), "getter should return nil when property is nil")
	})

	t.Run("GetWspdavg_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspdavg() // Should return zero value
	})

	t.Run("GetWspdhi", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Wspdhi = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetWspdhi(), "getter should return the property value")
	})

	t.Run("GetWspdhi_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Wspdhi = nil

		// Act & Assert
		assert.Nil(t, obj.GetWspdhi(), "getter should return nil when property is nil")
	})

	t.Run("GetWspdhi_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetWspdhi() // Should return zero value
	})

	t.Run("GetRainrate", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Rainrate = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRainrate(), "getter should return the property value")
	})

	t.Run("GetRainrate_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Rainrate = nil

		// Act & Assert
		assert.Nil(t, obj.GetRainrate(), "getter should return nil when property is nil")
	})

	t.Run("GetRainrate_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRainrate() // Should return zero value
	})

	t.Run("GetRain", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Rain = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetRain(), "getter should return the property value")
	})

	t.Run("GetRain_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Rain = nil

		// Act & Assert
		assert.Nil(t, obj.GetRain(), "getter should return nil when property is nil")
	})

	t.Run("GetRain_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetRain() // Should return zero value
	})

	t.Run("GetSolarrad", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Solarrad = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSolarrad(), "getter should return the property value")
	})

	t.Run("GetSolarrad_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Solarrad = nil

		// Act & Assert
		assert.Nil(t, obj.GetSolarrad(), "getter should return nil when property is nil")
	})

	t.Run("GetSolarrad_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSolarrad() // Should return zero value
	})

	t.Run("GetUvi", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Uvi = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetUvi(), "getter should return the property value")
	})

	t.Run("GetUvi_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Uvi = nil

		// Act & Assert
		assert.Nil(t, obj.GetUvi(), "getter should return nil when property is nil")
	})

	t.Run("GetUvi_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetUvi() // Should return zero value
	})

	t.Run("GetTempin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Tempin = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetTempin(), "getter should return the property value")
	})

	t.Run("GetTempin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Tempin = nil

		// Act & Assert
		assert.Nil(t, obj.GetTempin(), "getter should return nil when property is nil")
	})

	t.Run("GetTempin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetTempin() // Should return zero value
	})

	t.Run("GetHumin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *int
		obj.Humin = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHumin(), "getter should return the property value")
	})

	t.Run("GetHumin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Humin = nil

		// Act & Assert
		assert.Nil(t, obj.GetHumin(), "getter should return nil when property is nil")
	})

	t.Run("GetHumin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHumin() // Should return zero value
	})

	t.Run("GetHeatin", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var expected *float64
		obj.Heatin = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetHeatin(), "getter should return the property value")
	})

	t.Run("GetHeatin_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		obj.Heatin = nil

		// Act & Assert
		assert.Nil(t, obj.GetHeatin(), "getter should return nil when property is nil")
	})

	t.Run("GetHeatin_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetHeatin() // Should return zero value
	})

}

func TestSettersMarkExplicitDeviceValues(t *testing.T) {
	t.Run("SetEpoch_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueEpoch *int

		// Act
		obj.SetEpoch(fernTestValueEpoch)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTemp_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueTemp *float64

		// Act
		obj.SetTemp(fernTestValueTemp)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDew_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueDew *float64

		// Act
		obj.SetDew(fernTestValueDew)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetChill_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueChill *float64

		// Act
		obj.SetChill(fernTestValueChill)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeat_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueHeat *float64

		// Act
		obj.SetHeat(fernTestValueHeat)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHum_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueHum *int

		// Act
		obj.SetHum(fernTestValueHum)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBar_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueBar *float64

		// Act
		obj.SetBar(fernTestValueBar)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWdir_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueWdir *int

		// Act
		obj.SetWdir(fernTestValueWdir)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWdiravg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueWdiravg *int

		// Act
		obj.SetWdiravg(fernTestValueWdiravg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspd_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueWspd *float64

		// Act
		obj.SetWspd(fernTestValueWspd)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspdavg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueWspdavg *float64

		// Act
		obj.SetWspdavg(fernTestValueWspdavg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWspdhi_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueWspdhi *float64

		// Act
		obj.SetWspdhi(fernTestValueWspdhi)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRainrate_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueRainrate *float64

		// Act
		obj.SetRainrate(fernTestValueRainrate)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRain_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueRain *float64

		// Act
		obj.SetRain(fernTestValueRain)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSolarrad_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueSolarrad *float64

		// Act
		obj.SetSolarrad(fernTestValueSolarrad)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetUvi_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueUvi *float64

		// Act
		obj.SetUvi(fernTestValueUvi)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetTempin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueTempin *float64

		// Act
		obj.SetTempin(fernTestValueTempin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHumin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueHumin *int

		// Act
		obj.SetHumin(fernTestValueHumin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetHeatin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}
		var fernTestValueHeatin *float64

		// Act
		obj.SetHeatin(fernTestValueHeatin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingDeviceValues(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &DeviceValues{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled DeviceValues
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj DeviceValues
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj DeviceValues
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringDeviceValues(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &DeviceValues{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesDeviceValues(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &DeviceValues{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *DeviceValues
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
