// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	big "math/big"
	internal "sdk/internal"
)

// Live sensor readings
var (
	deviceValuesFieldEpoch    = big.NewInt(1 << 0)
	deviceValuesFieldTemp     = big.NewInt(1 << 1)
	deviceValuesFieldDew      = big.NewInt(1 << 2)
	deviceValuesFieldChill    = big.NewInt(1 << 3)
	deviceValuesFieldHeat     = big.NewInt(1 << 4)
	deviceValuesFieldHum      = big.NewInt(1 << 5)
	deviceValuesFieldBar      = big.NewInt(1 << 6)
	deviceValuesFieldWdir     = big.NewInt(1 << 7)
	deviceValuesFieldWdiravg  = big.NewInt(1 << 8)
	deviceValuesFieldWspd     = big.NewInt(1 << 9)
	deviceValuesFieldWspdavg  = big.NewInt(1 << 10)
	deviceValuesFieldWspdhi   = big.NewInt(1 << 11)
	deviceValuesFieldRainrate = big.NewInt(1 << 12)
	deviceValuesFieldRain     = big.NewInt(1 << 13)
	deviceValuesFieldSolarrad = big.NewInt(1 << 14)
	deviceValuesFieldUvi      = big.NewInt(1 << 15)
	deviceValuesFieldTempin   = big.NewInt(1 << 16)
	deviceValuesFieldHumin    = big.NewInt(1 << 17)
	deviceValuesFieldHeatin   = big.NewInt(1 << 18)
)

type DeviceValues struct {
	// Unix timestamp of reading
	Epoch *int `json:"epoch,omitempty" url:"epoch,omitempty"`
	// Temperature (°C)
	Temp *float64 `json:"temp,omitempty" url:"temp,omitempty"`
	// Dew point (°C)
	Dew *float64 `json:"dew,omitempty" url:"dew,omitempty"`
	// Wind chill (°C)
	Chill *float64 `json:"chill,omitempty" url:"chill,omitempty"`
	// Heat index (°C)
	Heat *float64 `json:"heat,omitempty" url:"heat,omitempty"`
	// Relative humidity (%)
	Hum *int `json:"hum,omitempty" url:"hum,omitempty"`
	// Barometric pressure (hPa)
	Bar *float64 `json:"bar,omitempty" url:"bar,omitempty"`
	// Instantaneous wind direction (°)
	Wdir *int `json:"wdir,omitempty" url:"wdir,omitempty"`
	// Average wind direction (°)
	Wdiravg *int `json:"wdiravg,omitempty" url:"wdiravg,omitempty"`
	// Instantaneous wind speed (m/s)
	Wspd *float64 `json:"wspd,omitempty" url:"wspd,omitempty"`
	// Average wind speed (m/s)
	Wspdavg *float64 `json:"wspdavg,omitempty" url:"wspdavg,omitempty"`
	// Wind gust / high speed (m/s)
	Wspdhi *float64 `json:"wspdhi,omitempty" url:"wspdhi,omitempty"`
	// Rain rate (mm/h)
	Rainrate *float64 `json:"rainrate,omitempty" url:"rainrate,omitempty"`
	// Total rain (mm)
	Rain *float64 `json:"rain,omitempty" url:"rain,omitempty"`
	// Solar radiation (W/m²)
	Solarrad *float64 `json:"solarrad,omitempty" url:"solarrad,omitempty"`
	// UV index (standard units, not ×10 — can be fractional, e.g. 0.9)
	Uvi *float64 `json:"uvi,omitempty" url:"uvi,omitempty"`
	// Inside temperature (°C) — requires authentication
	Tempin *float64 `json:"tempin,omitempty" url:"tempin,omitempty"`
	// Inside relative humidity (%) — requires authentication
	Humin *int `json:"humin,omitempty" url:"humin,omitempty"`
	// Inside heat index (°C) — requires authentication
	Heatin *float64 `json:"heatin,omitempty" url:"heatin,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeviceValues) GetEpoch() *int {
	if d == nil {
		return nil
	}
	return d.Epoch
}

func (d *DeviceValues) GetTemp() *float64 {
	if d == nil {
		return nil
	}
	return d.Temp
}

func (d *DeviceValues) GetDew() *float64 {
	if d == nil {
		return nil
	}
	return d.Dew
}

func (d *DeviceValues) GetChill() *float64 {
	if d == nil {
		return nil
	}
	return d.Chill
}

func (d *DeviceValues) GetHeat() *float64 {
	if d == nil {
		return nil
	}
	return d.Heat
}

func (d *DeviceValues) GetHum() *int {
	if d == nil {
		return nil
	}
	return d.Hum
}

func (d *DeviceValues) GetBar() *float64 {
	if d == nil {
		return nil
	}
	return d.Bar
}

func (d *DeviceValues) GetWdir() *int {
	if d == nil {
		return nil
	}
	return d.Wdir
}

func (d *DeviceValues) GetWdiravg() *int {
	if d == nil {
		return nil
	}
	return d.Wdiravg
}

func (d *DeviceValues) GetWspd() *float64 {
	if d == nil {
		return nil
	}
	return d.Wspd
}

func (d *DeviceValues) GetWspdavg() *float64 {
	if d == nil {
		return nil
	}
	return d.Wspdavg
}

func (d *DeviceValues) GetWspdhi() *float64 {
	if d == nil {
		return nil
	}
	return d.Wspdhi
}

func (d *DeviceValues) GetRainrate() *float64 {
	if d == nil {
		return nil
	}
	return d.Rainrate
}

func (d *DeviceValues) GetRain() *float64 {
	if d == nil {
		return nil
	}
	return d.Rain
}

func (d *DeviceValues) GetSolarrad() *float64 {
	if d == nil {
		return nil
	}
	return d.Solarrad
}

func (d *DeviceValues) GetUvi() *float64 {
	if d == nil {
		return nil
	}
	return d.Uvi
}

func (d *DeviceValues) GetTempin() *float64 {
	if d == nil {
		return nil
	}
	return d.Tempin
}

func (d *DeviceValues) GetHumin() *int {
	if d == nil {
		return nil
	}
	return d.Humin
}

func (d *DeviceValues) GetHeatin() *float64 {
	if d == nil {
		return nil
	}
	return d.Heatin
}

func (d *DeviceValues) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeviceValues) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetEpoch sets the Epoch field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetEpoch(epoch *int) {
	d.Epoch = epoch
	d.require(deviceValuesFieldEpoch)
}

// SetTemp sets the Temp field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetTemp(temp *float64) {
	d.Temp = temp
	d.require(deviceValuesFieldTemp)
}

// SetDew sets the Dew field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetDew(dew *float64) {
	d.Dew = dew
	d.require(deviceValuesFieldDew)
}

// SetChill sets the Chill field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetChill(chill *float64) {
	d.Chill = chill
	d.require(deviceValuesFieldChill)
}

// SetHeat sets the Heat field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetHeat(heat *float64) {
	d.Heat = heat
	d.require(deviceValuesFieldHeat)
}

// SetHum sets the Hum field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetHum(hum *int) {
	d.Hum = hum
	d.require(deviceValuesFieldHum)
}

// SetBar sets the Bar field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetBar(bar *float64) {
	d.Bar = bar
	d.require(deviceValuesFieldBar)
}

// SetWdir sets the Wdir field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetWdir(wdir *int) {
	d.Wdir = wdir
	d.require(deviceValuesFieldWdir)
}

// SetWdiravg sets the Wdiravg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetWdiravg(wdiravg *int) {
	d.Wdiravg = wdiravg
	d.require(deviceValuesFieldWdiravg)
}

// SetWspd sets the Wspd field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetWspd(wspd *float64) {
	d.Wspd = wspd
	d.require(deviceValuesFieldWspd)
}

// SetWspdavg sets the Wspdavg field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetWspdavg(wspdavg *float64) {
	d.Wspdavg = wspdavg
	d.require(deviceValuesFieldWspdavg)
}

// SetWspdhi sets the Wspdhi field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetWspdhi(wspdhi *float64) {
	d.Wspdhi = wspdhi
	d.require(deviceValuesFieldWspdhi)
}

// SetRainrate sets the Rainrate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetRainrate(rainrate *float64) {
	d.Rainrate = rainrate
	d.require(deviceValuesFieldRainrate)
}

// SetRain sets the Rain field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetRain(rain *float64) {
	d.Rain = rain
	d.require(deviceValuesFieldRain)
}

// SetSolarrad sets the Solarrad field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetSolarrad(solarrad *float64) {
	d.Solarrad = solarrad
	d.require(deviceValuesFieldSolarrad)
}

// SetUvi sets the Uvi field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetUvi(uvi *float64) {
	d.Uvi = uvi
	d.require(deviceValuesFieldUvi)
}

// SetTempin sets the Tempin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetTempin(tempin *float64) {
	d.Tempin = tempin
	d.require(deviceValuesFieldTempin)
}

// SetHumin sets the Humin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetHumin(humin *int) {
	d.Humin = humin
	d.require(deviceValuesFieldHumin)
}

// SetHeatin sets the Heatin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeviceValues) SetHeatin(heatin *float64) {
	d.Heatin = heatin
	d.require(deviceValuesFieldHeatin)
}

func (d *DeviceValues) UnmarshalJSON(data []byte) error {
	type unmarshaler DeviceValues
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeviceValues(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeviceValues) MarshalJSON() ([]byte, error) {
	type embed DeviceValues
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeviceValues) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// [unix_timestamp, value]
type TimestampValue = []float64
