// Code generated by Fern. DO NOT EDIT.

package stations_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	weathercloud "github.com/MauroDruwel/weathercloud-go"
	client "github.com/MauroDruwel/weathercloud-go/client"
	option "github.com/MauroDruwel/weathercloud-go/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestStationsGetNearbyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &weathercloud.GetNearbyStationsRequest{
		Lat: 1.1,
		Lon: 1.1,
		Km:  1,
	}
	_, invocationErr := client.Stations.GetNearby(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetNearbyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetNearbyWithWireMock", "GET", "/page/coordinates/latitude/1.1/longitude/1.1/distance/1", nil, 1)
}

func TestStationsGetPopularWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &weathercloud.GetPopularStationsRequest{
		Country: "BE",
		Period:  weathercloud.GetPopularStationsRequestPeriodDay,
	}
	_, invocationErr := client.Stations.GetPopular(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetPopularWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetPopularWithWireMock", "GET", "/page/popular/country/BE/period/day", nil, 1)
}

func TestStationsGetNewestWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &weathercloud.GetNewestStationsRequest{
		Country: "BE",
	}
	_, invocationErr := client.Stations.GetNewest(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetNewestWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetNewestWithWireMock", "GET", "/page/newest/country/BE", nil, 1)
}

func TestStationsGetMostFollowedWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &weathercloud.GetMostFollowedStationsRequest{
		Country: "BE",
	}
	_, invocationErr := client.Stations.GetMostFollowed(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetMostFollowedWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetMostFollowedWithWireMock", "GET", "/page/followers/country/BE", nil, 1)
}

func TestStationsGetLastViewsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Stations.GetLastViews(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetLastViewsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetLastViewsWithWireMock", "GET", "/page/lastviews", nil, 1)
}

func TestStationsGetOwnWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.Stations.GetOwn(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetOwnWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetOwnWithWireMock", "GET", "/page/own", nil, 1)
}

func TestStationsGetStationPageWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewWeathercloudClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &weathercloud.GetStationPageStationsRequest{
		DeviceID: "deviceId",
	}
	_, invocationErr := client.Stations.GetStationPage(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStationsGetStationPageWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStationsGetStationPageWithWireMock", "GET", "/ddeviceId", nil, 1)
}
