// Code generated by Fern. DO NOT EDIT.

package auth

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Authenticates a user session to allow viewing private indoor sensors (`tempin`, `humin`, `heatin`) for the user's station.
// This endpoint expects form urlencoded data and returns a `302 Found` redirect on successful login.
func (c *Client) Login(
	ctx context.Context,
	request *sdk.LoginAuthRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Login(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
