// Code generated by Fern. DO NOT EDIT.

package forecast

import (
	context "context"

	weathercloud "github.com/MauroDruwel/weathercloud-go"
	core "github.com/MauroDruwel/weathercloud-go/core"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	option "github.com/MauroDruwel/weathercloud-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (c *Client) GetDaily(
	ctx context.Context,
	request *weathercloud.GetDailyForecastRequest,
	opts ...option.RequestOption,
) (*weathercloud.ForecastResponse, error) {
	response, err := c.WithRawResponse.GetDaily(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
