// Code generated by Fern. DO NOT EDIT.

package map_

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns stations visible on the map for a given location bounding box.
//
// > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.
func (c *Client) GetDevices(
	ctx context.Context,
	request *sdk.GetDevicesMapRequest,
	opts ...option.RequestOption,
) (*sdk.MapDevicesResponse, error) {
	response, err := c.WithRawResponse.GetDevices(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetBackgroundDevices(
	ctx context.Context,
	request *sdk.GetBackgroundDevicesMapRequest,
	opts ...option.RequestOption,
) (*sdk.MapDevicesResponse, error) {
	response, err := c.WithRawResponse.GetBackgroundDevices(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetMetars(
	ctx context.Context,
	request map[string]any,
	opts ...option.RequestOption,
) (*sdk.GetMetarsMapResponse, error) {
	response, err := c.WithRawResponse.GetMetars(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
