// Code generated by Fern. DO NOT EDIT.

package stations

import (
	context "context"
	sdk "sdk"
	core "sdk/core"
	internal "sdk/internal"
	option "sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns nearby stations as JSON (despite `text/html` content-type header).
// All `page/*` endpoints return `PageDevice` objects that include the **station name**.
// Values are scaled integers — divide by 10 (e.g. `temp: 281` = 28.1°C).
func (c *Client) GetNearby(
	ctx context.Context,
	request *sdk.GetNearbyStationsRequest,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetNearby(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetPopular(
	ctx context.Context,
	request *sdk.GetPopularStationsRequest,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetPopular(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetNewest(
	ctx context.Context,
	request *sdk.GetNewestStationsRequest,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetNewest(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetMostFollowed(
	ctx context.Context,
	request *sdk.GetMostFollowedStationsRequest,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetMostFollowed(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetLastViews(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetLastViews(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

func (c *Client) GetOwn(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.PageDevicesResponse, error) {
	response, err := c.WithRawResponse.GetOwn(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The station **name** is not available from any JSON API endpoint.
// The easiest way to get it is to fetch the station's HTML page and extract
// the name from the `<title>` or `og:title` meta tag.
//
// **Example response title:**
// ```
// WeatherStation Skyline - Weathercloud | Global network of weather stations
// ```
//
// Strip everything from ` - Weathercloud` onward to get the clean station name.
//
// > This is a plain HTML page, not a JSON API. Use it for scraping only.
func (c *Client) GetStationPage(
	ctx context.Context,
	request *sdk.GetStationPageStationsRequest,
	opts ...option.RequestOption,
) (string, error) {
	response, err := c.WithRawResponse.GetStationPage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}
