// Code generated by Fern. DO NOT EDIT.

package devicelive

import (
	context "context"

	weathercloud "github.com/MauroDruwel/weathercloud-go"
	core "github.com/MauroDruwel/weathercloud-go/core"
	internal "github.com/MauroDruwel/weathercloud-go/internal"
	option "github.com/MauroDruwel/weathercloud-go/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Returns the latest sensor values for a device. **No CSRF token needed.**
// This is the primary endpoint for a Home Assistant sensor integration.
func (c *Client) GetValues(
	ctx context.Context,
	request *weathercloud.GetValuesDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.DeviceValues, error) {
	response, err := c.WithRawResponse.GetValues(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns current values plus day/month/year min and max for all sensors.
// Each value is a `[unix_timestamp, value]` tuple.
func (c *Client) GetStats(
	ctx context.Context,
	request *weathercloud.GetStatsDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.DeviceStats, error) {
	response, err := c.WithRawResponse.GetStats(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Station name, location, elevation, equipment info.
func (c *Client) GetInfo(
	ctx context.Context,
	request *weathercloud.GetInfoDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.DeviceInfo, error) {
	response, err := c.WithRawResponse.GetInfo(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Wind direction distribution data for the wind rose chart.
func (c *Client) GetWindRose(
	ctx context.Context,
	request *weathercloud.GetWindRoseDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.WindData, error) {
	response, err := c.WithRawResponse.GetWindRose(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns seconds since last update and device online status.
//
// > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.
func (c *Client) GetUpdateStatus(
	ctx context.Context,
	request *weathercloud.GetUpdateStatusDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.GetUpdateStatusDeviceLiveResponse, error) {
	response, err := c.WithRawResponse.GetUpdateStatus(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns observer name, follower count, and device brand/model.
//
// > ⚠️ **Requires `X-Requested-With: XMLHttpRequest`** header — without it the server returns an empty 200.
func (c *Client) GetOwnerProfile(
	ctx context.Context,
	request *weathercloud.GetOwnerProfileDeviceLiveRequest,
	opts ...option.RequestOption,
) (*weathercloud.DeviceProfile, error) {
	response, err := c.WithRawResponse.GetOwnerProfile(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
